
<div class="content wbg-wrapper" style="background:url(/img/aboutbg.jpg) center top no-repeat;background-attachment: fixed;background-size:cover;">
    <div class="container_24">
        <div class='grid_24'>
            <div style="padding:100px 0;color:#fff;text-align:center;">
                <p style="font-size:42px;">
                    ROCKPAPA
                </p>
                <div style="height:3px;background:#FFF;width:100px;margin:0 auto 10px auto;"></div>
                <p>
                    Designing and producing high quality and stylish headphones
                </p>
                
                <div style="padding:30px;border:2px solid #FFF;line-height:28px;width:250px;margin:50px auto 0 auto;">
                    <div style="font-weight:bold;">ADDRESS: </div>
                    <div style="margin-bottom:10px;">
                        7C，Lushan Ge,Fengjingtai Dasha,Yijing Lu,Luohu,Shenzhen,GuangDong,China
                    </div>
                    <div style="font-weight:bold;">CONTACT: </div>
                    <div>
                        Mr Wang, 15814000410
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>