
<div class="content wbg-wrapper" style="background:url(/img/aboutbg.jpg) center top no-repeat;background-attachment: fixed;background-size:cover;">
    <div class="container_24">
        <div class='grid_24'>
            <div style="padding:100px 0;color:#fff;text-align:center;">
                <p style="font-size:42px;">
                    ROCKPAPA
                </p>
                <div style="height:3px;background:#FFF;width:100px;margin:0 auto 10px auto;"></div>
                <p>
                    Designing and producing high quality and stylish headphones
                </p>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>