<?php
    if(isset($this->isTokenExpired) && ($this->isTokenExpired === true)){
?>
<div class="container_24 main">
    <div class="grid_24">
            <div class="emailsent">
                <p class="songti">对不起，我们无法激活你的天使圈帐号，因为你的帐号激活链接已经失效。请点击下面的按钮，我们将重新发送一封帐号激活邮件到你的邮箱。谢谢！</p>
                <div class="clear_10px"></div>
                <input id="resendmail" class="btn resend" value="重新发送帐号激活邮件"/>
            </div>
    </div>
</div>
<script type="text/javascript">
    (function($){
	var resendmailObj = $('#resendmail');
	resendmailObj.click( function(){
            resendmailObj.validResultHide();
            resendmailObj.processBtn('发送中...');
            $.post("<?php echo $this->url(array(), 'wait-to-be-activated')?>", null, function(result){
                if(result === 1){
                    resendmailObj.val('已成功发送');
                    resendmailObj.validResultShow('right','发送成功请前往邮箱查看', 70, 10);
                } else {
                    resendmailObj.validResultShow('error','发送失败，请重试', -30, 50);
                }
            });
        });
    })(jQuery);
</script>

<?php
    }
?>

<?php
    if(isset($this->isValidatedSuccess) && ($this->isValidatedSuccess === true)){
?>
<div class="container_24 main">
<div class="grid_24">
	<div class="emailsent">
                <p class="songti"><strong class="yahei"><?php echo $this->user->username ?></strong>，你已经成功激活了你的天使圈帐号。</p>
                <div class="clear_10px"></div>
                <a href="/login" id="checkmailbox" class="btn resend">立即登录</a>
        </div>
</div>
</div>
<?php
    }
?>

<script type="text/javascript">
    (function($){
	$('body').addClass('loginpage');
    })(jQuery);
</script>

