
<div class="content">
    <div class="container_24">
        <div class="grid_6">
            &nbsp;
        </div>
        <div class="grid_12 wbg-wrapper pad">
            <span class="tot"></span>
            <div class="pad-20">
                <p class="tt nomargin bold font16px"><?php echo $this->title ?></p>
                <p class="nomargin">input your register email then we will send new password to your inbox.</p>
                <input type="text" id="email" placeholder="REGISTER EMAIL" class="stxt"/>
                <div class="clear-20"></div>
                <div class="text-center">
                    <button type="button" id="change-pwd" class="btn btn-default btn-lg"><i class="halflings ok"></i> Submit</button>
                </div>
                <div class="clear-10"></div>
            </div>
        </div>
        <div class="grid_6">
            &nbsp;
        </div>
    </div>

</div>

<script type="text/javascript">

    (function($) {
        $(document).ready(function() {
            $('#email').focus();
        });
        $('#change-pwd').click(function() {
            var email = $('#email').val();
            if (email.isEmail()) {
                var data = {email: email};
                $.waiting({msg: 'Processing ...'});
                
                var sendBean = {width:500};
                
                $.ajax({
                    url: '<?php echo $this->url(array(), 'forgot-password') ?>',
                    data: data,
                    dataType: 'json',
                    type: 'post',
                    success: function(response) {
                        if (response) {
                            sendBean.msg = '<i class="glyphicons circle_ok green t2"></i><br/>Success. We sent new password to your email inbox.';
                            $.alertbox(sendBean);
                        } else {
                            sendBean.msg = '<i class="glyphicons warning_sign red t2"></i><br/>Sorry failed to reset password. Please confirm it is correct email';
                            $.alertbox(sendBean);
                        }
                    },
                    complete: function() {
                        $.endWaiting();
                    }
                });
            } else {
                $.alertbox({msg: '<i class="t2 glyphicons warning_sign red t2"></i><br/>Please input correct email.'});
            }

        });

    })(jQuery);

</script>

<style>
    .pad {
        position:relative;
        box-shadow:0 1px 2px rgba(0,0,0,0.05);
    }
    .tt {
        margin-bottom:15px;
        padding-bottom:10px;
        border-bottom:1px solid #F0F0F0;
    }
    .content {
        margin-top:20px;
    }
    #email {
        box-sizing: border-box;
        margin-top:10px;
        height:36px;
        line-height:36px;
        width:100%;
    }
    .tot {
        background: #FFD800;
        height:16px;
        left:0;
        top:24px;
        position:absolute;
        width:8px;
    }
    .t2 {
        font-size:32px;
    }
</style>