<div class="container_24 main">
    <div class="grid_24 board relative">
        <h1 class="shorttitle">
        密码找回
        </h1>
        <div class="inputs">
            <div class="input email">
                <span class="title">输入邮箱</span>
                <input type="text" id="email" enterclickobjid="retrievebtn" class="txt enterclick" />
            </div>
            <div class="clear_20px"></div>
            <input type="button" id="retrievebtn" class="btn" value="找回密码"/>
        </div>
    </div>
</div>
<script type="text/javascript">
    (function($){
        
        $('body').addClass('loginpage');
        
        var clickBtn = $('#retrievebtn');
        var emailObj = $('#email');
        
        clickBtn.click(function(){
            
            clickBtn.validResultHide();
            emailObj.validResultHide();
            if(!validateInput(emailObj)){
                return;
            }
            
            var data = {email:emailObj.val()};
            clickBtn.processBtn('发送中...');
            $.post('/forgotpwd', data, function(result){
                if(result === 1) {
                    clickBtn.val('发送成功');
                    clickBtn.validResultShow('right','新密码已经发送至你的邮箱，请立刻查收',70, 10);
                } else {
                    // 发送失败
                    clickBtn.validResultShow('error','操作失败，请确定该邮箱已注册过',70, 10);
                    clickBtn.processBtnRestore();
                }
            });
        });
        
        function validateInput(emailObj) {
            var result = true;

            // CHECKING EMAIL
            var reg = REG_EMAIL;
            var email = emailObj.val();
            if (reg.test(email)) {

            } else {
                    emailObj.validResultShow('error','请输入正确的邮箱',100);
                    result = false;
            }

            return result;
	}
    })(jQuery);
</script>