<style>
    .sign-up-now {
        display: block;
        padding: 10px;
        -webkit-border-radius: 6px;
        -moz-border-radius: 6px;
        -ms-border-radius: 6px;
        -o-border-radius: 6px;
        border-radius: 6px;
        -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.5), 0 1px 0 rgba(255, 255, 255, 0.5);
        -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.5), 0 1px 0 rgba(255, 255, 255, 0.5);
        -ms-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.5), 0 1px 0 rgba(255, 255, 255, 0.5);
        -o-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.5), 0 1px 0 rgba(255, 255, 255, 0.5);
        box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.5), 0 1px 0 rgba(255, 255, 255, 0.5);
        border: 1px solid rgba(14, 41, 57, 0.1);
        color: #455b67;
        font-size: 13px;
        font-weight: bold;
        text-align: center;
        color: #999;
    }
    .sign-up-now:hover {
        color: #333;
    }
    .sign-in-now {
        height: 42px;
        width: 100%;
        background: linear-gradient(#7dc5ee, #008cdd 85%, #30a2e4);
        box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.25);
    }
    .sign-in-now:hover {
        border-color: #369;
    }
    .sign-in-now:active {
        background: linear-gradient(#7dc5ee, #008cdd 85%, #30a2e4);
    }
    .sign-txt {
        border: 1px solid #aaa !important;
        border-radius: 4px !important;
        box-sizing: border-box !important;
        width: 100% !important;
        height: 42px !important;
        line-height: 42px !important;
        padding: 0 15px !important;
        box-shadow: inset 0 1px 2px rgba(0, 0, 0, .1) !important;
        background: #FBFBFB !important;
        outline: none;
        font-weight: bold;
    }
    .sign-txt:focus,
    .sign-txt:hover {
        background: #FFF !important;
    }
    .sign-txt:focus {
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, .2) !important;
    }
    .sign-ttx {
        text-shadow: 0 1px 1px rgba(255, 255, 255, .75);
        font-size: 32px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 20px;
    }
    .sign-ttx .xxtt {
        font-family: georgia;
    }
    .sign-ttx .xxtt2 {
        font-weight: lighter;
        color: #aaa;
        font-size: 14px;
        text-align: center;
    }
    .sign-bbct {
        margin: auto;
        width: 320px;
    }
    .sign-bbct .miwio9 {
        
        border-radius: 4px;
        margin-bottom: 20px;
    }
    .sign-bbct .miwio9 .ct {
        padding:20px 20px 30px 20px;
    }
    .sign-bbct .px001 {
        text-align:center;
    }
    .sign-bbct .px002 {
        font-size:14px;
        font-family:Gotham A;
        display:inline-block;
        padding-bottom:8px;
        padding-top:5px;
        margin-bottom:25px;
        border-bottom:1px solid rgba(0,0,0,.05);
        font-weight: 500;
    }
    .sign-bbct .px003 {
        margin-bottom:15px;
    }
    .sign-remember-me-txt {
        margin-left:5px;
        font-size:12px;
        float:left;
        color:#aaa;
        cursor: pointer;
    }
    #sign-remember-me {
        float:left;
        margin-top:2px;
        cursor: pointer;
    }
</style>
<div style="padding:40px 0;">
    <div class="sign-ttx">
        <div class="xxtt">REGISTER</div>
        <div class="xxtt2">
            - Best service for you -
        </div>
    </div>
    <div class="sign-bbct">

        <div class="miwio9 classicbg">
            <div class="ct">
                <div class="px001">
                    <span class="px002">Welcome to DRIFTBOT!</span>
                </div>
                <div class="px003">
                    <input type="text" class="sign-txt" placeholder="Email" />
                </div>
                <div class="px003">
                    <input type="password" class="sign-txt" placeholder="Password" />
                </div>
                <div>
                    <button class="btn btn-primary sign-in-now">Submit</button>
                </div>
            </div>
        </div>

        <a href="javascript:void(0)" id="login-now-btn" class="sign-up-now">
            I have account. Login now
        </a>
    </div>

</div>

<script type="text/javascript">
    (function($) {
        $('#login-now-btn').click(function() {
            if($('#login-btn').length) {
                $('#login-btn').click();
            } else {
                alert('sorry you have already signed in');
            }
        });
    })(jQuery);
</script>