<h1 class="page-title"><?php echo $this->title ?></h1>

<form role="form" method="post">
    <div class="row">
        <div class="col-md-4">

            <?php if ($this->register): ?>
                <div class="alert alert-success">注册成功，请登录</div>
            <?php endif; ?>
            <?php if ($this->error): ?>
                <div class="alert alert-danger"><?php echo $this->error ?></div>
            <?php endif; ?>

            <div class="form-group">
                <label for="email">邮箱</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="输入邮箱">
            </div>
            <div class="form-group">
                <label for="password">密码</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="输入密码">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="remember" name="remember"> 记住登录状态
                </label>
            </div>
            <button type="submit" class="btn btn-default">安全登录</button>
        </div>
        <div class="col-md-4"></div>
    </div>
</form>

<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>