
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> 记住登录状态
                </label>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>

    </div>
    <div class="col-md-4"></div>

</div>

<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>