<style>


    .itm {
    }
    .wp {
        background:#F0F0F0;
        margin-bottom:30px;
        padding:15px;
    }
    .wp p {
        font-size:12px;
    }
    .iwp {
        height:230px;
        overflow:hidden;
        position:relative;
        width:100%;
    }
    .iwp img {
        left:0;
        position:absolute;
        top:0;
    }
    .wp label {
        color:#5cb85c;
    }
    .btb {
        padding:20px 0;
        text-align:right;
    }
    .wp ul {
        display:block;
        margin:15px 0 0;
        padding:0;
    }
    .wp ul li {
        display:inline-block;
        margin-bottom:10px;
        margin-right:5px;
        list-style: none;
    }
    .btn-group {
        margin-top:15px;
    }
</style>
<?php
$model = $this->model;
?>
<div class="btb">
    <input type="button" id="clear-cache" class="btn btn-success" value="清除缓存图片" />
</div>
<div class="row">
    <?php foreach ($this->resource as $p): ?>
        <div class="col-md-3 itm">
            <input type="hidden" class="tmp" value="<?php echo $p['name'] ?>"/>
            <div class="wp">
                <div class="iwp">
                    <img width="100%" src="<?php echo $p['path']['main'] ?>"/>
                </div>
                <div class="btn-group">
                    <a href="<?php echo $p['path']['small'] ?>" target="_blank" class="btn btn-default btn-sm">小</a>
                    <a href="<?php echo $p['path']['main'] ?>" target="_blank" class="btn btn-default btn-sm">中</a>
                    <a href="<?php echo $p['path']['large'] ?>" target="_blank" class="btn btn-default btn-sm">大</a>
                    <a href="<?php echo $p['path']['xlarge'] ?>" target="_blank" class="btn btn-default btn-sm">超</a>
                    <a href="<?php echo $p['path']['orig'] ?>" target="_blank" class="btn btn-success btn-sm">原</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    (function($) {
        $('#clear-cache').click(function() {
            $.ajax({
                url: '/manage/photo/clearcache',
                dataType: 'json',
                type: 'POST',
                complete: function(response) {
                    console.log(response);
                    alert('操作成功');
                }
            });
        });
    })(jQuery);
</script>
