<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>图片分类标题：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>图片分类描述：</label>
                <input type="text" class="form-control" id="description" name="description" data-toggle="popover" value="">
            </div>

            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>