<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>图片标题：</label>
                <input type="text" class="form-control" id="title" name="title" data-toggle="popover" value="<?php echo $this->model->title ?>">
            </div>
            <div class="form-group">
                <label>图片描述：</label>
                <input type="text" class="form-control" id="description" name="description" data-toggle="popover" value="<?php echo $this->model->description ?>">
            </div>
            <div class="form-group">
                <label>图片分类：</label>
                <select id="phototype" name="phototype" value="<?php echo $this->model->phototype->id ?>">
                    <option value="">未选中</option>
                    <?php foreach ($this->phototype as $key => $val): ?>
                        <option value="<?php echo $val->id ?>"><?php echo $val->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('#phototype').setSelectValue();
    })(jQuery);
</script>
