<style>


    .itm {
    }
    .wp {
        background:#F0F0F0;
        margin-bottom:30px;
        padding:15px;
    }
    .wp p {
        font-size:12px;
        margin:0;
    }
    .iwp {
        height:230px;
        margin-top:15px;
        overflow:hidden;
        position:relative;
        width:100%;
    }
    .iwp img {
        left:0;
        position:absolute;
        top:0;
    }
    .pwp {
        margin:10px 0;
    }
    .wp label {
        color:#5cb85c;
    }
    .wp ul {
        display:block;
        margin:5px 0 0;
        padding:0;
    }
    .wp ul li {
        display:inline-block;
        margin-bottom:10px;
        margin-right:5px;
        list-style: none;
    }
    .btn-group {
        margin-top:0;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="btb">
    <a id="clear-cache" class="btn btn-success" href="<?php echo $this->url(array(), 'manage-product-create') ?>">新建商品</a>
</div>
<div class="row">
    <?php foreach ($this->resource as $p): ?>
        <div class="col-md-3 itm">
            <input type="hidden" class="tmp" value="<?php echo $p['id'] ?>"/>
            <div class="wp">
                <p><?php echo $p['owner']->email . ' 上传' ?>
                    <button class="pull-right btn btn-xs btn-danger remove-product">删除</button>
                </p>
                <div class="iwp">
                    <img width="100%" src="<?php echo $p['path'] ?>"/>
                </div>
                <div class='pwp'>
                    <p><?php echo $p['title'] ?></p>
                    <p><i><?php echo $p['sub_title'] ?></i></p>
                </div>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array(), 'manage-product-save') . '?id=' . $p['id'] ?>" class="btn btn-info btn-sm">编辑</a>
                    <a href="<?php echo $this->url(array(), 'manage-product-save') . '?copy=true&&id=' . $p['id'] ?>" class="btn btn-default btn-sm">复制</a>

                    <a target="_blank" href="<?php echo $this->url(array('id' => $p['id']), 'product-view') . '/' . $p['title'] ?>" class="btn btn-default btn-sm">预览</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <?php echo $this->partial('manage/partials/_paginator_bar.phtml', array('current_page_no' => $this->paginator->getCurrentPageNumber(), 'page_count' => $this->paginator->count(), 'route_name' => 'manage-product-list')); ?>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.remove-product').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-product-remove') ?>');
        });
    })(jQuery);
</script>
