
<div class="row">
    <div class="col-md-8">
        <h1 class="page-title"><?php echo $this->title ?></h1>
        <form role="form">
            <div class="form-group">
                <label>商品全称：</label>
                <input type="text" class="form-control" id="title">
            </div>
            <div class="form-group">
                <label>商品简称：</label>
                <input type="text" class="form-control" id="short_title">
            </div>
            <div class="form-group">
                <label>商品附标题：</label>
                <input type="text" class="form-control" id="sub_title">
            </div>
            <div class="form-group">
                <label>商品唯一编号：</label>
                <input type="text" class="form-control" id="sku">
            </div>
            <div class="form-group">
                <label>商品状态：</label>
                <select id="status">
                    <option value="online" selected="true">在线出售</option>
                    <option value="soldout">售完</option>
                </select>
            </div>
            <div class="form-group">
                <label>描述：</label>
                <textarea row="10" class="form-control" id="description"></textarea>
            </div>
            <div class="form-group">
                <label>商品所在地（仓储）：</label>
                <input type="text" class="form-control" id="location" value="cn">
            </div>
            <div class="form-group">
                <label>采购价：</label>
                <input type="number" class="form-control" id="base_price">
            </div>
            <div class="form-group">
                <label>售价：</label>

                <div class="input-group input-group">
                    <span class="input-group-addon">$ USD</span>
                    <input type="number" class="form-control">
                </div>

                <div class="input-group input-group">
                    <span class="input-group-addon">£ GBP</span>
                    <input type="number" class="form-control">
                </div>
                
                <div class="input-group input-group">
                    <span class="input-group-addon">€ EUR</span>
                    <input type="number" class="form-control">
                </div>
                
                <div class="input-group input-group">
                    <span class="input-group-addon">$ HKD</span>
                    <input type="number" class="form-control">
                </div>
                
                <div class="input-group input-group">
                    <span class="input-group-addon">$ AUD</span>
                    <input type="number" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label>商品品牌：</label>
                
            </div><div class="form-group">
                <label>商品分类：</label>
                
            </div>
            
            <button type="submit" disabled="disabled" class="btn btn-default">确认提交</button>
            
        </form>
    </div>
</div>

<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>