<h1 class="page-title"><?php echo $this->title ?></h1>
<form role="form" method="post">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="email">邮箱</label>
                <input type="email" class="form-control" id="email" placeholder="输入邮箱">
            </div>
            <div class="form-group">
                <label for="pwd">密码</label>
                <input type="password" class="form-control" id="pwd" placeholder="输入密码">
            </div>
            <div class="form-group">
                <label for="repwd">确认密码</label>
                <input type="password" class="form-control" id="repwd" placeholder="再次输入密码">
            </div>
            <button type="submit" class="btn btn-default">确认注册</button>

        </div>
        <div class="col-md-4"></div>
    </div>
</form>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>