<h1 class="page-title"><?php echo $this->title ?></h1>
<form role="form" method="post">
    <div class="row">
        <div class="col-md-4">
            <?php if ($this->error): ?>
                <div class="alert alert-danger"><?php echo $this->error ?></div>
            <?php endif; ?>
            <div class="form-group">
                <label for="email">邮箱</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="输入邮箱">
            </div>
            <div class="form-group">
                <label for="password">密码</label>
                <input type="password" class="form-control" maxlength="18" id="password" name="password" placeholder="输入密码">
            </div>
            <div class="form-group">
                <label for="repwd">确认密码</label>
                <input type="password" class="form-control" id="repwd" placeholder="再次输入密码">
            </div>
            <button type="submit" id="reg" class="btn btn-default">确认注册</button>

        </div>
        <div class="col-md-4"></div>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        $('#reg').click(function() {
            if ($('#password').val() !== $('#repwd').val()) {
                alert('两次输入密码不相同，请重试');
                return false;
            }
        });
    })(jQuery);
</script>