<div class="sideblock">
    <div class="head">
            345条留言
    </div>
    <div class="feeds">
            <div class="feed">
                    <div class="feedcontent">
                            <p class="songti font14px"><strong>以后就背这个包去中东战乱国家做人道主义救援</strong></p>
                            <div class="clear_5px"></div>
                            <p class="songti font14px gray">同伪军宅+驴友表示这个真的很有吸引力。。但是说到防弹什么的话，可能因为是女孩子不会想那么多，而且平时出行也不会去那么危险的地方。只要材质上满足一般行程需要就觉得很满意了~</p>
                            <div class="clear_5px"></div>
                            <i>By Sinna</i><i class="lightgray">发布于</i><i>2013年1月12日</i>
                            <a href="#" class="photo">
                                    <img src="img/photos/person2.jpg"/>
                            </a>
                    </div>
            </div>

            <div class="feed">
                    <div class="feedcontent">
                            <p class="songti font14px"><strong>以后就背这个包去中东战乱国家做人道主义救援</strong></p>
                            <div class="clear_5px"></div>
                            <p class="songti font14px gray">同伪军宅+驴友表示这个真的很有吸引力。。但是说到防弹什么的话，可能因为是女孩子不会想那么多，而且平时出行也不会去那么危险的地方。只要材质上满足一般行程需要就觉得很满意了~</p>
                            <div class="clear_5px"></div>
                            <i>By Sinna</i><i class="lightgray">发布于</i><i>2013年1月12日</i>
                            <a href="#" class="photo">
                                    <img src="img/photos/person3.jpg"/>
                            </a>
                    </div>
            </div>

            <div class="feed">
                    <div class="feedcontent">
                            <p class="songti font14px"><strong>以后就背这个包去中东战乱国家做人道主义救援</strong></p>
                            <div class="clear_5px"></div>
                            <p class="songti font14px gray">同伪军宅+驴友表示这个真的很有吸引力。。但是说到防弹什么的话，可能因为是女孩子不会想那么多，而且平时出行也不会去那么危险的地方。只要材质上满足一般行程需要就觉得很满意了~</p>
                            <div class="clear_5px"></div>
                            <i>By Sinna</i><i class="lightgray">发布于</i><i>2013年1月12日</i>
                            <a href="#" class="photo">
                                    <img src="img/photos/person1.jpg"/>
                            </a>
                    </div>
            </div>

            <div class="feed">
                    <div class="feedcontent">
                            <p class="songti font14px"><strong>以后就背这个包去中东战乱国家做人道主义救援</strong></p>
                            <div class="clear_5px"></div>
                            <p class="songti font14px gray">同伪军宅+驴友表示这个真的很有吸引力。。但是说到防弹什么的话，可能因为是女孩子不会想那么多，而且平时出行也不会去那么危险的地方。只要材质上满足一般行程需要就觉得很满意了~</p>
                            <div class="clear_5px"></div>
                            <i>By Sinna</i><i class="lightgray">发布于</i><i>2013年1月12日</i>
                            <a href="#" class="photo">
                                    <img src="img/photos/person2.jpg"/>
                            </a>
                    </div>
            </div>
    </div>
    <div class="aligncenter x03">
            <a class="btn commentbtn">
                    我要评论
                    <span class="icon"></span>
            </a>
    </div>
</div>