<div style="font-family:'Microsoft Yahei';font-size:13px;margin:auto;width:600px;">
    <p style="background:#F8F8F8;padding:20px;text-align:center;margin:0">
        <a href="<?php echo $this->domain_url ?>">
                <img width="120" src="<?php echo $this->domain_url.$this->imagePath('logo.png'); ?>" style="border:0"/>
        </a>
    </p>
    <div style="background:#FFF;padding:20px;margin:0">
        <?php echo $this->layout()->content; ?>
        <p style="padding-top: 10px">
            <?php echo strtoupper($this->site_name) ?> TEAM
            <br/>
            <?php echo date('m/d/Y')?>
        </p>
    </div>

    <p style="background:#F8F8F8;font-size:12px;padding:20px;text-align:center;margin:0">
        <a href="<?php echo $this->domain_url; ?>" style="text-decoration:none;color:#BBB !important;">visit <?php echo $this->site_name?></a> 
    </p>
</div>