<!DOCTYPE html>
<html>
    <head>
        <title>VERYCART | WHERE TO BUY AMAZING</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("reset.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("text.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("960gs.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("open-sans.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("global.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("global.mall.css"); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("sub.css"); ?>" />
        <link rel="icon" href="/favicon.ico" mce_href="/favicon.ico" type="image/x-icon" />

        <script type="text/javascript" src="<?php echo $this->jsPath('jquery.1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('global.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('plugin.js'); ?>"></script>
        <script type="text/javascript">
            $(document).ready(function() {
//                $.currency.init();
//                $('#cart-total').html($.cart.total());
                $('#login-btn').click(function() {
                    var options = {
                        content: $('.login-window').clone(true),
                        padding: 0,
                        modal: true,
                        width: 400
                    };
                    $.popup(options);
                });
                $('#my-username').clickToggle();
            });
        </script>
    </head>

    <body>
        <div class="P_tmp">

            <div class="login-window">
                <div class="hd">
                    <div class="btn-group">
                        <a href="javascript:void(0)" tag="login" class="btn selected" onclick="switchLoginWindowTo(this)">Member Login</a>
                        <a href="javascript:void(0)" tag="register" class="btn" onclick="switchLoginWindowTo(this)">Register Now</a>
                    </div>
                </div>
                <div class="frm login-board">
                    <div class="form-c">
                        <i class="halflings envelope"></i>
                        <input class="email_val nothing-txt" type="text" placeholder="Email"/>
                    </div>

                    <div class="form-c mg">
                        <i class="glyphicons keys"></i>
                        <input class="password_val nothing-txt" type="password" placeholder="Password"/>
                    </div>

                    <div class="valid-result mg red text-center"><i class="halflings warning-sign"></i> <span>Oops! Password does not match. Please try again</span></div>

                    <button class="mg" onclick="login(this, '<?php echo $this->url(array(), 'login') ?>')">Login</button>
                    <div class="forgot-pwd"><a href="<?php echo $this->url(array(), 'forgot-password') ?>">Forgot password</a></div>
                    <div class="clear-line"></div>
                    <p class="text-center">Not a member yet ? <a href="javascript:void(0)" tag="register" onclick="switchLoginWindowTo(this)" class="red">Register now</a></p>
                </div>

                <div class="frm register-board">
                    <div class="form-c">
                        <i class="halflings envelope"></i>
                        <input class="email_val nothing-txt" type="text" placeholder="Email"/>
                    </div>
                    <div class="form-c">
                        <i class="halflings user"></i>
                        <input class="nick_name_val nothing-txt" type="text" placeholder="Nick Name"/>
                    </div>
                    <div class="form-c mg">
                        <i class="glyphicons keys"></i>
                        <input class="password_val nothing-txt" type="password" placeholder="Password"/>
                    </div>


                    <div class="valid-result mg red text-center"><i class="halflings warning-sign"></i> <span>Oops! Password does not match. Please try again</span></div>
                    <button class="mg" onclick="register(this, '<?php echo $this->url(array(), 'register') ?>')">Register</button>
                    <div class="clear-line"></div>
                    <p class="text-center">Already a member ? <a href="javascript:void(0)" tag="login" onclick="switchLoginWindowTo(this)" class="red">Login</a></p>
                </div>
            </div>
        </div>
        <!-- Top Start -->
        <div class="wp top clearfix">
            <div class="container_24">
                <div class="grid_5">
                    <a href="#" class="logo l-ft"><img src="/img/logo.png" alt="welcome to sitename"/></a>
                </div>
                <div class="grid_14">
                    <img src="/img/P92033858697.38329-4"/>
<!--                    <div class="search-bar">
                        <input type="text" placeholder="Search keywords or model #" />
                    </div>-->
                </div>
                <div class="grid_5">
                    <div class="info-bar">
                        <div class="l-ft">
                            <?php if (!isset($this->me)): ?>
                            <a href="#" id="login-btn" class="btn btn-sm btn-default">Login / Register</a>
                            <?php else: ?>
                                <span class="light-gray">hey</span> <a href="#" id="my-username" rel="my-settings"><?php echo $this->me->getUser()->username ?></a>


                            <?php endif; ?>
                        </div>
<!--                        <span class="vsplr l-ft"></span>
                        <div class="cart-bar l-ft">
                            Cart
                            <a id="cart-total" href="<?php echo $this->url(array(), 'cart') ?>"> 0 </a>
                        </div>
                        <span class="vsplr l-ft"></span>

                        <div class="currency-bar l-ft">
                        <?php foreach ($this->currency as $key => $val): ?>
                                    <a class="price-option" currency="<?php echo $key ?>" currency-symbol="<?php echo $this->currency_symbol[$key] ?>" href="javascript:void(0)"> <?php echo $this->currency_symbol[$key] . ' ' . $key ?> </a>
                        <?php endforeach; ?>
                        </div>-->
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="grid_24 hot-tags">
                    <a href="#"> Just Shopping </a>
                    <span class="vsplr"></span>
                    <a href="#"> All Categories </a>
                    <span class="vsplr"></span>
                    <a href="#"> New Arrivals </a>
                    <span class="vsplr"></span>
                    <a href="#"> Apple Accessory </a>
                    <span class="vsplr"></span>
                    <a href="#"> Samsung Accessory </a>
                    <span class="vsplr"></span>
                    <a href="#"> Kids Gift </a>

                    <div class="addthis-block">
                        <!-- AddThis Button BEGIN -->
                        <!--                        <div class="addthis_toolbox addthis_default_style ">
                                                    <a class="addthis_button_preferred_1"></a>
                                                    <a class="addthis_button_preferred_2"></a>
                                                    <a class="addthis_button_preferred_3"></a>
                                                    <a class="addthis_button_preferred_4"></a>
                                                    <a class="addthis_button_compact"></a>
                                                    <a class="addthis_counter addthis_bubble_style"></a>
                                                </div>
                                                <script type="text/javascript">
                                                    var addthis_config = {
                                                        "data_track_addressbar": true
                                                    };
                                                </script>
                                                <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f4a185e7d9e1842"></script>-->
                        <!-- AddThis Button END -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Top End -->
        <!-- Content Start -->
        <?php echo $this->layout()->content; ?>
        <!-- Content End -->

        <!-- Bottom Start -->
        <div style="padding:20px 0;text-align:center;">
            <img src="/img/logo.png" />
        </div>
        <!-- Bottom End -->

        <div id="my-settings" class="dropdown-list click-toggle">
            <div class="dropdown-itm">
                <i class="halflings map-marker"></i>
                <a href="<?php echo $this->url(array(), 'user-address') ?>">Update Address</a>
            </div>
            <!--            <div class="dropdown-itm">
                            <a href="<?php echo $this->url(array(), 'user-order') ?>">Orders</a>
                        </div>-->
            <div class="dropdown-itm">
                <a href="<?php echo $this->url(array(), 'reset-password') ?>">Reset Password</a>
            </div>
            <div class="divider"></div>
            <div class="dropdown-itm">
                <i class="halflings off"></i>
                <a href="<?php echo $this->url(array(), 'logout') ?>">Logout</a>
            </div>
        </div>

    </body>
</html>
