<!DOCTYPE html>
<html>
<head>
<title>天使圈(中国)</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("reset.css"); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("text.css"); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("960_24_col.css"); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("global.css"); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("sub.css"); ?>" />

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->jsPath('plugin.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->jsPath('global.js'); ?>"></script>
<script type="text/javascript">
    $(document).ready(function(){
            init();
    });
</script>
</head>

<body class="relative">
    <div class="top">
        <div class="container_24">
            <div class="grid_4 relative logowrapper">
                <a href="<?php echo $this->url(array(), 'company-list')?>" class="logo">欢迎来到 Angelhere</a>
            </div>
            <div class="grid_20">
                <ul class="nav">
                    <li>
                        <a href="#" class="searchbt"><span></span>搜索</a>
                    </li>
                    <li>
                        <a href="#">创业项目</a>
                    </li>
                    <li>
                        <a href="#">金牌投资人</a>
                    </li>
                    <li>
                        <a href="#">服务介绍</a>
                    </li>
                    <li>
                        <a href="#">关于我们</a>
                    </li>
                </ul>
                
                <?php
                    if(isset($this->me)){
                        ?>
                <div class="userboard">
                    你好，
                    <a href="<?php echo $this->url(array(), 'profile')?>"><?php echo($this->me->getUser()->username); ?></a> - 
                    <a href="<?php echo $this->url(array(), 'logout') ?>">安全退出</a>
                </div>
                <?php
                        
                    } else {
                        ?>
                <a href="<?php echo $this->url(array(), 'register')?>" class="register">注册</a>
                <span class="orsplit">or</span>
                <a href="<?php echo $this->url(array(), 'login')?>" class="login">登录</a>
                
                <?php    
                    }
                ?>
                
                <a href="#" class="contactus">联系我们</a>
            </div>
        </div>
    </div>
    
    <?php echo $this->layout()->content; ?>

    <div class="bottom fullwrapper">
        <div class="container_24 ">
            <div class="grid_12 left">
                <div class="relative">
                    <a href="#" class="logo"></a>
                    <span class="x01">已为创业团队募集资金总额</span>
                </div>
                <div class="x02">
                    <ul class="counter">
                        <li>￥</li>
                        <li>1</li>
                        <li>,</li>
                        <li>2</li>
                        <li>2</li>
                        <li>2</li>
                        <li>,</li>
                        <li>0</li>
                        <li>0</li>
                        <li>0</li>
                    </ul>
                </div>
            </div>
            <div class="grid_12 right">
                <ul>
                    <li class="title">关于我们</li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">加入我们</a></li>
                    <li></li>
                </ul>
                <ul>
                    <li class="title">合作伙伴</li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>
                <ul>
                    <li class="title">地区 / Location</li>
                    <li><a href="#">中国</a></li>
                    <li><a href="#">U.S.A</a></li>
                    <li></li>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>
