<form id="pay" name="pay" action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_xclick">
    <input type="hidden" name="business" value="bus1@a.com">
    <input type="hidden" name="lc" value="C2">
    <input type="hidden" name="item_name" value="test">
    <input type="hidden" name="amount" value="1.00">
    <input type="hidden" name="currency_code" value="DKK">
    <input type="hidden" name="button_subtype" value="services">
    <input type="hidden" name="return" value="http://www.gisbuy.com/paypal/return">
    <input type="hidden" name="notify_url" value="http://www.gisbuy.com/paypal/notify">
    <input type="hidden" name="no_note" value="0">
    <input type="hidden" name="tax_rate" value="0.000">
    <input type="hidden" name="shipping" value="0.00">
    <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHostedGuest">
    <input type="image" src="https://www.paypalobjects.com/zh_XC/C2/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal——最安全便捷的在线支付方式！">
    <img alt="" border="0" src="https://www.paypalobjects.com/zh_XC/i/scr/pixel.gif" width="1" height="1">
</form>

