
<div class="content wbg-wrapper">

    <div class="container_24" id="order-block">
        <div class="grid_24">

            <div class="user-page-lnk btn-group">
                <a href="<?php echo $this->url(array(), 'user-address') ?>" class="btn">Update Address</a>
                <a href="<?php echo $this->url(array(), 'user-order') ?>" class="btn selected">Orders</a>
                <a href="<?php echo $this->url(array(), 'reset-password') ?>" class="btn">Reset Password</a>
            </div>
            <?php if (count($this->orders)): ?>
                <ul class="clearfix" id="order-header">
                    <li class="oid">Order #<span class="splr"></span></li>
                    <li class="address">Address<span class="splr"></span></li>
                    <li class="order-detail">Order Detail<span class="splr"></span></li>
                    <li class="status">Status</li>
                </ul>
                <div id="order-container">
                    <?php foreach ($this->orders as $order): ?>
                        <div oid="<?php echo $order->oid ?>" ts="<?php echo $order->created_at->getTimestamp(); ?>" class="order-itm clearfix">

                            <ul>
                                <li class="oid">
                                    <i class="light-gray">#</i> <?php echo $order->oid ?>
                                    <br/>
                                    <p style='font-size:smaller;color:#999;'><?php echo $order->created_at->format('jS F y') ?></p>
                                </li>
                                <li class="address">
                                    <div class="pad">
                                        <?php if ($order->selected_address_type == 2): ?>
                                            <div style="background-color:#F8F8F8;color:#999;font-size:smaller;text-align:center;margin-bottom:15px;">Paypal Address</div>
                                        <?php endif; ?>
                                        <p class="clearfix"><span class="l1">contact</span><span class="l2"><?php echo $order->address->contact ? $order->address->contact : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">phone</span><span class="l2"><?php echo $order->address->phone ? $order->address->phone : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">street</span><span class="l2"><?php echo $order->address->street ? $order->address->street : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">city</span><span class="l2"><?php echo $order->address->city ? $order->address->city : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">state / county</span><span class="l2"><?php echo $order->address->state ? $order->address->state : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">zip / postal code</span><span class="l2"><?php echo $order->address->zip ? $order->address->zip : '-- --' ?></span></p>
                                        <p class="clearfix"><span class="l1">country</span><span class="l2"><?php echo $order->address->country ? $order->address->country : '-- --' ?></span></p>
                                    </div>

                                </li>
                                <li class="order-detail">
                                    <div class="pad">
                                        <?php if ($order->order_detail): ?>
                                            <?php $count = 1; ?>
                                            <?php foreach ($order->order_detail as $order_detail): ?>
                                                <ol>
                                                    <li style="position:relative;min-height:34px;">
                                                        <a target="_blank" href="<?php echo $this->url(array(id => $order_detail->product_id), 'product-view') ?>">
                                                            <?php echo $count . '. ' . $order_detail->product_title ?>
                                                        </a>
                                                        <div style="font-size:smaller;color:#999;">
                                                            <p>price &nbsp;&nbsp; <?php echo $this->currency_symbol_options[$order->currency] . $order_detail->price . $order->currency ?> &nbsp;&nbsp; / &nbsp;&nbsp; qty &nbsp;&nbsp; <?php echo $order_detail->unit . 'pcs' ?></p>
                                                            <p></p>

                                                        </div>
                                                    </li>
                                                </ol>
                                                <?php $count++; ?>
                                            <?php endforeach; ?>
                                            <p style="color:#ef3546;text-align:center;border-top:1px dotted #bbb;padding-top:10px;margin-top:10px;">
                                                TOTAL IS : <?php echo $this->currency_symbol_options[$order->currency] . $order->total . $order->currency ?>
                                            </p>
                                        <?php endif; ?>
                                    </div>
                                </li>
                                <li class="status">
                                    <div class="pad">
                                        <?php
                                        $statusCls = "";
                                        $iconCls = "";
                                        if ($order->status == 1) {
                                            $statusCls = "light-gray";
                                            $iconCls = "glyphicons more";
                                        } else if ($order->status == 2) {
                                            $statusCls = "green";
                                            $iconCls = "glyphicons cargo";
                                        } else if ($order->status == 3) {
                                            $statusCls = "cyan";
                                            $iconCls = "glyphicons airplane";
                                        } else if ($order->status == 4) {
                                            $statusCls = "red";
                                            $iconCls = "glyphicons gift";
                                        } else if ($order->status == 5) {
                                            $statusCls = "orange";
                                            $iconCls = "glyphicons thumbs_up";
                                        }
                                        ?>
                                        <div class="<?php echo $statusCls ?>">
                                            <i class="<?php echo $iconCls ?>"></i>
                                            <p style='margin-bottom:10px'><?php echo $this->order_status_options[$order->status] ?></p>
                                        </div>
                                        <?php if ($order->status == 1): ?>
                                            <a href='#' class="btn" style="font-size:smaller;margin-bottom:5px;display:block;padding:0;">Pay Now</a>
                                            <a href='#' class="btn" style="font-size:smaller;margin-bottom:5px;display:block;padding:0;">Delete</a>
                                        <?php elseif ($order->status == 2): ?>
                                            <p class="green" style="padding:5px;line-height:18px;font-size:smaller;background:#d0e9c6;">
                                                Thanks we got payment and item is dispatching for you.
                                            </p>
                                        <?php elseif ($order->status == 3): ?>
                                            <p class="cyan" style="padding:5px;line-height:18px;font-size:smaller;background:#c4e3f3;">
                                                <?php
                                                if($order->shipped_at) {
                                                    $t = $order->shipped_at->format('jS F Y');
                                                    $r1 = date_add($order->shipped_at, date_interval_create_from_date_string('10 days'))->format('jS F');
                                                    $r2 = date_add($order->shipped_at, date_interval_create_from_date_string('15 days'))->format('jS F');
                                                }
                                                
                                                ?>
                                                Item shipped on <?php echo $t ?>. Normally you will get it between <?php echo $r1?> to <?php echo $r2 ?>  
                                            </p>
                                        <?php endif; ?>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>



</div>

<script type="text/javascript">

    (function($) {

    })(jQuery);

</script>

<style>
    .order-itm {
        border-bottom:1px solid #DDD;
        padding:15px 0;
    }
    .order-itm:hover {
        border-color:#bbb;
    }
    .order-itm ul {
        display:block;
    }
    .order-itm ul li {
        display: block;
        line-height:24px;
        float:left;
    }
    .order-itm ul li .pad {
        padding:0 15px;
    }
    .order-itm ul li.oid, #order-header .oid {
        width:130px;
    }
    .order-itm ul li.oid {
        text-align:center;
    }
    .order-itm ul li.address, #order-header .address {
        width:300px;
    }
    .order-itm ul li.order-detail, #order-header .order-detail {
        width:320px;
    }
    .order-itm ul li.status, #order-header .status {
        text-align:center;
        width:200px;
    }
    .order-itm ul li .l1, .order-itm ul li .l2 {
        display:inline-block;
        float:left;
        width:140px;
    }
    .order-itm ul li .l1 {
        color:#999;
    }
    .order-itm ul li .l2 {
        width:130px;
    }
    #order-header li {
        /*        border-top:1px solid #aaa;
                border-bottom:1px solid #aaa;*/
        background:#F8F8F8;
        display:inline-block;
        float:left;
        padding:10px 0;
        position:relative;
        text-align:center;
    }
    #order-header li .splr {
        height:100%;
        position:absolute;
        right:0;
        width:1px;
        top:0;
        display:block;
        background:#FFF;
    }
    .order-detail ol {
    }
    .order-detail ol li {
        display:block;
        float:none;
    }

    /*    #order-header li:nth-child(even)
        {
            background:#FBFBFB;
        }*/
</style>