<!DOCTYPE html>
<html>
<head>
    <title>上传头像</title>
</head>

<body>
    <form method="post" action="<?php echo $this->url(array(), 'personal-thumbnail')?>" enctype="multipart/form-data">
        <input type="file" name="thumbnail" accept="image/*"/>
        <input type="hidden" name="status" value="<?php echo $this->result; ?>"/>
        <?php
        
            if(isset($this->path)){
        ?>
                <input type="hidden" name="path" value="<?php echo $this->path; ?>"/>
        <?php
            }
        ?>
    </form>
</body>
</html>