<?php
    $user = $this->me->getUser();
    $wait_tobe_validate = $user->wait_tobe_validate;
    if(isset($wait_tobe_validate) && $wait_tobe_validate == 1){
        $wait_tobe_validate = true;
    } else {
        $wait_tobe_validate = false;
    }
?>
<div class="container_24 main">
<div class="clear_50px"></div>
<?php echo $this->partial('user/partials/_usersetting_nav.phtml', array('selected'=>'resetpwd', 'usertype'=>$user->user_type )); ?>
<div class="grid_21 radiusall_4px mainbody">
    <div class="leftmargin50px">
        <?php echo $this->partial('user/partials/_show_validate_tip.phtml', array('user'=>$user)); ?>
    <div class="relative">
        <h1 class="pagetitle">
        用户资料 - 修改密码
        </h1>

        <div class="clear_20px"></div>

        <table class="submittable">
            <tr>
                <td class="col1">原密码</td>
                <td><input type="password" id="old" class="ntext"/></td>
            </tr>
            <tr>
                <td>新密码</td>
                <td><input type="password" id="new" class="ntext"/></td>
            </tr>
            <tr>
                <td>确认新密码</td>
                <td><input type="password" id="renew" class="ntext"/></td>
            </tr>
        </table>

        <div class="boldline nomargin"></div>
        <div class="clear_20px"></div>

        <input type="button" id="savebtn" value="保存" class="btn"/>
        <div class="clear_50px"></div>
    </div>
    </div>
</div>
</div>
<script type="text/javascript">
    (function($){
        
        $('body').addClass('my');
        var oldPwd = $('#old')
        var newPwd = $('#new');
        var renewPwd = $('#renew');
        newPwd.inputTip('请设置长度大于6位的密码');
        
        $('#savebtn').click(function(e){
            $.validResultClear();
            if(newPwd.val() === renewPwd.val()) {
                if(newPwd.val().length >= 6) {
                    $(e.target).processBtn('正在保存...');
                    $.post('/resetpwd', {'new':newPwd.val(), 'old':oldPwd.val()}, function (result){
                        $(e.target).processBtnRestore();
                        if(result === 1) {
                            $(e.target).validResultShow('right', '密码修改成功', 70, 10);
                        } else {
                            $(e.target).validResultShow('error', result, 70, 10);
                        }
                    })
                } else {
                    newPwd.validResultShow('error','密码的长度必须大于6位',30);
                }
            } else {
                renewPwd.validResultShow('error','前后两次输入不一致，请重试',30);
            }
        });
        
        
    })(jQuery);
</script>
        