
<div class="content wbg-wrapper">

    <div class="container_24" id="address-block">
        <div class="grid_24">


            <div class="user-page-lnk btn-group">
                <a href="<?php echo $this->url(array(), 'user-address') ?>" class="btn">Update Address</a>
                <a href="<?php echo $this->url(array(), 'user-order') ?>" class="btn">Orders</a>
                <a href="<?php echo $this->url(array(), 'reset-password') ?>" class="btn selected">Reset Password</a>
            </div>

            <div>
                <div class="simple-panel text-center">
                    NOTICE: Please set password longer than 8 chars for safe reason
                </div>
                <div class="clear-15"></div>
                <div class="ct">
                    <div class="ftb full nlm">
                        <p class="ftbp">
                            <i class="glyphicons keys"></i>
                            <input type="password" class="nothing-txt" id="old-pwd" title="OLD PASSWORD" placeholder="OLD PASSWORD" value="">

                        </p>
                        <span class="top-c">OLD PASSWORD</span>
                    </div>
                    <div class="clear"></div>
                    <div class="ftb nlm">
                        <p class="ftbp">
                            <i class="glyphicons lock"></i>
                            <input type="password" class="nothing-txt" id="new-pwd" title="NEW PASSWORD" placeholder="NEW PASSWORD" value="">
                        </p>
                        <span class="top-c">NEW PASSWORD</span>
                    </div>
                    <div class="ftb">
                        <p class="ftbp">
                            <i class="glyphicons rotation_lock"></i>
                            <input type="password" class="nothing-txt" id="re-pwd" title="RE-CONFIRM PASSWORD" placeholder="RE-CONFIRM PASSWORD" value="">
                        </p>
                        <span class="top-c">RE-CONFIRM PASSWORD</span>
                    </div>
                </div>
            </div>
            
            
            <div class="clear-20"></div>
            <div class="text-center">
                <button type="button" id="save-pwd" class="btn btn-default btn-lg"><i class="halflings floppy_save"></i> Save password</button>
            </div>
            <div class="clear-50"></div>
        </div>
    </div>



</div>

<script type="text/javascript">

    (function($) {
        switchTopC();

        $('.ftb').click(function() {
            var $this = $(this).closest('.ftb');
            var txt = $this.find('.nothing-txt');
            if (txt.length) {
                txt.focus();
            }

        });
        $('.ftb .nothing-txt').keyup(function() {
            switchTopC();
        });
        
        $('#old-pwd').focus();
    })(jQuery);

</script>

<style>
    .ftb .nothing-txt, .ftb.full .nothing-txt {
        width:80% !important;
    }

</style>