

<div class="content">
    <div class="container_24">
        <div class="grid_24">
            <h1><?php echo $this->title ?></h1><span style="color:#888;">fast shipping service for you</span>
        </div>
        <div class="grid_24" id="cart-list">
            <table>
                <thead>
                    <tr>
                        <th class="col1 cart-photo"></th>
                        <th class="col2 cart-title">Product</th>
                        <th class="col3 cart-price">Price</th>
                        <th class="col4 cart-qty">Qty</th>
                        <th class="col5 cart-subtotal">Subtotal</th>
                        <th class="col6 cart-operation"></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="P_tmp">
    <table>
        <tr class="cart-list-itm">
            <td class="col1 cart-photo"></td>
            <td class="col2 cart-title"></td>
            <td class="col3 cart-price"></td>
            <td class="col4 cart-qty"></td>
            <td class="col5 cart-subtotal"></td>
            <td class="col6 cart-operation"></td>
        </tr>
    </table>
    <div class="price" price="0" currency="usd">
        <span class="price-str">0</span>
    </div>
</div>

<script type="text/javascript">
    function requestCart() {
        var query = $.cart.parse();
        if (!query) {
            // empty handle
            return;
        }
        var data = new Array();
        $.each(query, function(k, v) {
            data.push(k);
        });
        var s = data.join('|');
        data = {query: s};
        $.ajax({
            url: '<?php echo $this->url(array(), 'cart') ?>',
            dataType: 'json',
            type: 'post',
            data: data,
            success: function(response) {
                if (response.code === 200) {
                    $.each(response.data, function() {
                        var $this = this;
                        var row = $('.P_tmp .cart-list-itm').clone(true);

                        var selling_price = $this.selling_price;
                        var qty = query[$this.id];
                        $.each(selling_price, function(k, v) {
                            // set price
                            var price = $('.P_tmp .price').clone(true);
                            price.attr('price', v.amount);
                            price.find('.price-str').html(v.symbol + v.amount + k);
                            price.attr('currency', k);
                            row.find('.cart-price').append(price);
                            // set subtotal
                            var subtotal = $('.P_tmp .price').clone(true);
                            
                            subtotal.attr('price', qty * v.amount);
                            subtotal.find('.price-str').html(v.symbol + qty * v.amount + k);
                            subtotal.attr('currency', k);
                            row.find('.cart-subtotal').append(subtotal);
                        });
                        // set photo
                        row.find('.cart-photo').append($('<img>').attr('src', $this['photo']));
                        // set qty
                        row.find('.cart-qty').append($('<input>').attr('type', 'number').val(qty));
                        row.find('.cart-title').append($('<a>').attr('target', '_blank').attr('href', $this.link).html($this.title));
                        $('#cart-list tbody').append(row);
                    });

                }
            }
        });
    }

    (function($) {
        requestCart();
    })(jQuery);
</script>

<style>
    #cart-list thead tr th {
        background:#F0F0F0;
        color:#aaa;
    }
</style>