<?php
$address = array();
if ($this->me && $this->me->getUser()->address) {
    $address = $this->me->getUser()->address;
}
?>

<div class="content wbg-wrapper">
    <div class="container_24">
        <div class="grid_10">
            <h1 class="nomargin"><?php echo $this->title ?></h1><span class="subtt-checkout">Fast shipping service for you</span>
        </div>
        <div class="grid_14">
            <div id="pay-proc">
                <div class="red" id="step1">
                    <i class="glyphicons shopping_cart"></i>
                    Shopping Cart
                </div>

                <div class="light-gray" id="step2">
                    <i class="halflings barcode"></i>
                    Address &amp; Shipping
                </div>

                <div class="light-gray" id="step3">
                    <i class="halflings saved"></i>
                    Payment Complete
                </div>

                <div id="proc">
                    <div id="inner" style="width:10%"></div>
                </div>
            </div>
        </div>
        <div class="grid_24" id="cart-list">
            <table>
                <thead>
                    <tr>
                        <th class="col1 cart-photo"></th>
                        <th class="col2 cart-title">Product</th>
                        <th class="col3 cart-price">Price</th>
                        <th class="col4 cart-qty">Qty</th>
                        <th class="col5 cart-subtotal">Subtotal</th>
                        <th class="col6 cart-operation"></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
        <div class="grid_24" id="cart-empty">
            <p>Sorry your shopping cart is empty.</p>
            <a href="/" class="btn">Continue shopping</a>
        </div>
    </div>
    <div class="container_24" id="pay-info">
        <div class="grid_14">
            &nbsp;
        </div>
        <div class="grid_5">
            <p class="right-float">total is</p>
        </div>
        <div class="grid_5">
            <p id="total" class="right-float"></p>
            <button id="checkout-btn" class="checkout-btn green-btn right-float"><i class="halflings barcode"></i> Confirm &amp; Next</button>
        </div>
    </div>

    <div class="container_24 checkout" id="address-block">
        <div class="grid_10">
            <h1 class="nomargin">Address &amp; Shipping</h1><span class="subtt-checkout">Please input correct address</span>

        </div>
        <div class="grid_14">
            <div id="pay-proc">
                <div class="red" id="step1">
                    <i class="glyphicons shopping_cart"></i>
                    Shopping Cart
                </div>

                <div class="red" id="step2">
                    <i class="halflings barcode"></i>
                    Address &amp; Shipping
                </div>

                <div class="light-gray" id="step3">
                    <i class="halflings saved"></i>
                    Payment Complete
                </div>

                <div id="proc">
                    <div id="inner" style="width:50%"></div>
                </div>
            </div>
        </div>
        <div class="grid_24">

            <div class="btn-group address-type">

                <?php if (!$this->me) : ?>
                    <a href="javascript:void(0)" class="btn selected"><i class='halflings uni-paperclip'></i> Write address now</a>
                    <a href="javascript:void(0)" class="btn" id="login-and-load"><i class='halflings cloud_download'></i> Login &amp; Load my address</a>
                <?php else: ?>
                    <a href="javascript:void(0)" class="btn selected"><i class='halflings cloud'></i> My address</a>
                <?php endif; ?>
                <a href="javascript:void(0)" class="btn"><i class='font-paypal'></i> Use my paypal address</a>
            </div>

            <?php
            $updateBtn = false;
            if($this->me) {
                $updateBtn = true;
            }
            ?>
            <?php echo $this->partial('user/partials/_address_writer.phtml', array(address => $address, updateBtn => $updateBtn)); ?>

            <div class="clear-20"></div>
            <div class="text-center">
                <button type="submit" class="pp-btn"></button>
            </div>
            <div class="clear-50"></div>
        </div>
    </div>

</div>
<div class="P_tmp">
    <table>
        <tr class="cart-list-itm">
            <td class="col1 cart-photo"></td>
            <td class="col2 cart-title"></td>
            <td class="col3 cart-price"></td>
            <td class="col4 cart-qty"></td>
            <td class="col5 cart-subtotal"></td>
            <td class="col6 cart-operation"><button class="cart-remove-btn">&times;</button></td>
        </tr>
    </table>
    <div class="price" price="0" currency="">
        <span class="price-str">0</span>
    </div>
</div>

<script type="text/javascript">
    function requestCart() {
        var query = $.cart.parse();
        if (!query) {
            // empty handle
            return;
        }
        var data = new Array();
        $.each(query, function(k, v) {
            data.push(k);
        });
        var s = data.join('|');
        data = {query: s};

        $.ajax({
            url: '<?php echo $this->url(array(), 'cart') ?>',
            dataType: 'json',
            type: 'post',
            data: data,
            success: function(response) {
                var container = $('#cart-list table tbody');
                container.empty();
                if (response.code === 200) {
                    $.each(response.data, function() {
                        var $this = this;
                        var row = $('.P_tmp .cart-list-itm').clone(true);
                        row.attr('id', $this.id);
                        var selling_price = $this.selling_price;
                        var qty = query[$this.id];
                        $.each(selling_price, function(k, v) {
                            // set price
                            var price = $('.P_tmp .price').clone(true);
                            price.attr('price', v.amount);
                            price.attr('symbol', v.symbol);
                            price.find('.price-str').html(v.symbol + v.amount + k);
                            price.attr('currency', k);
                            row.find('.cart-price').append(price);
                            // set subtotal
                            var subtotal = $('.P_tmp .price').clone(true);
                            var a = (qty * v.amount).toFixed(2);
                            subtotal.attr('price', a);
                            subtotal.attr('symbol', v.symbol);
                            subtotal.find('.price-str').html(v.symbol + a + k);
                            subtotal.attr('currency', k);
                            row.find('.cart-subtotal').append(subtotal);
                        });
                        // set photo
                        row.find('.cart-photo').append($('<img>').attr('src', $this['photo']));
                        // set qty
                        var input = $('<input>').attr('type', 'text').attr('maxlength', 2).val(qty);
                        input.integerInput();
                        input.change(function() {
                            var qty = $(this).val();
                            var id = $(this).closest('tr').attr('id');
                            $.cart.set(id, parseInt(qty));
                            requestCart();
                        });
                        row.find('.cart-qty').append(input);
                        row.find('.cart-title').append($('<a>').attr('target', '_blank').attr('href', $this.link).html($this.title));
                        container.append(row);
                    });
                    // set pay-info
                    var tmps = {};
                    $.each($('#cart-list .cart-list-itm'), function() {
                        var $this = $(this);
                        var p = $this.find('.cart-subtotal .price');
                        $.each($(p), function() {
                            var $this = $(this);
                            if (tmps[$this.attr('currency')]) {
                                tmps[$this.attr('currency')].amount = (parseFloat(tmps[$this.attr('currency')].amount) + parseFloat($this.attr('price'))).toFixed(2);
                            } else {
                                tmps[$this.attr('currency')] = {amount: parseFloat($this.attr('price')), symbol: $this.attr('symbol')};
                            }
                        });
                    });
                    $('#pay-info #total').empty();
                    $.each(tmps, function(k, v) {
                        var row = $('.P_tmp .price').clone(true);
                        row.attr('price', v.amount);
                        row.attr('currency', k);
                        row.find('.price-str').html(v.symbol + v.amount + k);
                        $('#pay-info #total').append(row);
                    });
                    $('#pay-info').fadeIn(100);
                } else if (response.code === 404) {
                    $('#cart-list').hide();
                    $('#pay-info').hide();
                    $('#cart-empty').show();
                }
                $('#cart-total').html($.cart.total());
            },
            complete: function() {
                $.currency.refresh();
            }
        });
    }

    (function($) {
        requestCart();
        $('.cart-remove-btn').click(function() {
            var tr = $(this).closest('tr');
            $.cart.set(tr.attr('id'), 0);
            requestCart();
        });
        $('#checkout-btn').click(function() {
            if ($.cart.total()) {
                $('#address-block').show();
                $('html, body').animate({scrollTop: $('#pay-info').offset().top}, 300);
                $('#contact').focus();
            } else {
                var html = "<p class='marginbottom5px'>Sorry the cart is empty now.</p><button class='sm-btn black-btn' onclick='location.reload();'>Refresh Page</button>";
                $.alertbox({msg: html});
            }
        });
        $('.ftb').click(function() {
            var $this = $(this).closest('.ftb');
            var txt = $this.find('.nothing-txt');
            if (txt.length) {
                txt.focus();
            }

        });

        $('.ftb .nothing-txt').keyup(function() {
            switchTopC();
        });

        $('#login-and-load').click(function() {
            $.cookie('just-checkout', true);
            $('#login-btn').click();
        });


        // 检查所否刚刚正在填入地址的时候登录或者注册了，继续刚才的流程        
        if ($.cookie('just-checkout')) {
            $.removeCookie('just-checkout');
            var f = function() {
                $('#checkout-btn').click();
            };
            setTimeout(f, 1000);
        }
    })(jQuery);

</script>

<style>
    #cart-list table {
        width:100%;
    }
    #cart-list table th {
        background:#F0F0F0;
        color:#aaa;
        padding:5px 0;
        text-align:center;
    }
    #cart-list table td {
        border-bottom:1px solid #eee;
        padding:15px 0;
        text-align:center;
        width: 15%;
    }
    #cart-list table .col2 {
        width:20%;
    }

    #cart-list table .col6 {
        text-align:right;
    }
    #cart-list .cart-list-itm {
        padding:20px;
    }
    #cart-list .cart-list-itm input[type=text] {
        height:24px;
        line-height:24px;
        padding:0 5px;
        text-align:center;
        width:30px;
    }
    #cart-empty {
        border-bottom:1px solid #DDD;
        border-top:1px solid #DDD;
        display:none;
        margin-bottom:50px;
        padding-bottom:50px;
        padding-top:50px;
        text-align:center;
    }
    #cart-empty p {
        font-size:16px;
        padding-bottom:20px;
    }
    #cart-empty a {

    }

    #pay-info {
        display:none;
        font-size:15px;
        padding:20px 0;
    }
    #pay-info .grid_4 {
        text-align:right;
    }
    #pay-info #total * {
        color:#EF3546;
    }
    #checkout-btn {
        margin-top:20px;
    }
    .cart-remove-btn {
        background:transparent;
        color:#999;
        font-size:16px;
        height:20px;
        margin:0 10px 0 0;
        padding:0;
        width:20px;
    }
    .cart-remove-btn:hover {
        background:transparent;
        box-shadow:none;
        color:#333;
    }

    #address-block {
        display:none;
    }

</style>