

<div class="content">
    <div class="container_24">
        <div class="grid_24 marginbottom30px">
            <h1 class="nomargin"><?php echo $this->title ?></h1><span class="subt">please confirm the total amount for the order</span>
        </div>
        <div class="grid_24">
            <h2 style="font-size:15px;font-weight:bold;margin:0;border-left:5px solid #419641;padding:0 20px">
                Delivery Address
            </h2>
            <table>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>

<style>
</style>