

<div class="content checkout wbg-wrapper">
    <div class="container_24">
        <div class="grid_10">
            <h1 class="nomargin"><?php echo $this->title ?></h1><span class="subtt-checkout">please confirm the total amount for the order</span>
            
        </div>
        <div class="grid_14">
            <div id="pay-proc">
                <div class="red" id="step1">
                    <i class="glyphicons shopping_cart"></i>
                    Shopping Cart
                </div>
                
                <div class="red" id="step2">
                    <i class="halflings barcode"></i>
                    Checkout Order
                </div>
                
                <div class="light-gray" id="step3">
                    <i class="halflings saved"></i>
                    Payment Complete
                </div>
                
                <div id="proc">
                    <div id="inner" style="width:50%"></div>
                </div>
            </div>
        </div>
        <div class="grid_24">

            <div class="btn-group">
                <a href="javascript:void(0)" class="btn selected"><i class='halflings uni-paperclip'></i> Write it now</a>
                <a href="javascript:void(0)" class="btn"><i class='halflings cloud_download'></i> Login &amp; Load my address</a>
                <a href="javascript:void(0)" class="btn"><i class='font-paypal'></i> Use my paypal address</a>
            </div>

            <div>
                <div class="ftb nlm">
                    <p class="ftbp">
                        <i class="halflings user"></i>
                        <input type='text' class='nothing-txt' title="CONTACT" placeholder="CONTACT"/>

                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="ftb">
                    <p class="ftbp">
                        <i class="halflings phone_alt"></i>
                        <input type='text' class='nothing-txt' title="PHONE NUMBER" placeholder="PHONE NUMBER"/>
                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="clear"></div>
                <div class="ftb full nlm">
                    <p class="ftbp">
                        <i class="halflings home"></i>
                        <input type='text' class='nothing-txt' title="STREET ADDRESS" placeholder="STREET ADDRESS"/>
                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="clear"></div>
                <div class="ftb nlm">
                    <p class="ftbp">
                        <i class="halflings tag"></i>
                        <input type='text' class='nothing-txt' title="CITY" placeholder="CITY"/>
                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="ftb">
                    <p class="ftbp">
                        <i class="halflings tags"></i>
                        <input type='text' class='nothing-txt' title="STATE / COUNTY" placeholder="STATE / COUNTY"/>
                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="clear"></div>
                <div class="ftb nlm">
                    <p class="ftbp">
                        <i class="halflings envelope"></i>
                        <input type='text' class='nothing-txt' title="ZIP / POSTAL CODE" placeholder="ZIP / POSTAL CODE"/>
                    </p>
                    <span class="top-c"></span>
                </div>
                <div class="ftb">
                    <p class="ftbp">
                        <i class="halflings globe"></i>
                        <select title="COUNTRY">
                            <option>CHOOSE COUNTRY</option>
                            <option>United Kingdom</option>
                            <option>United States</option>
                            <option>Japan</option>
                            <option>Hong Kong</option>
                            <option>Germany</option>
                        </select>
                    </p>
                </div>
            </div>
            <div class="clear-20"></div>
            <div class="text-center">
                <button type="button" class="btn">Confirm &amp; Pay via Paypal</button>
            </div>
            <div class="clear-50"></div>
        </div>
    </div>
</div>
<style>
    .btn-group {
        margin-bottom:30px;
    }
    .nlm {
        border-left:none !important;
    }
    .nothing-txt {
        background:transparent !important;
        border:0;
        box-shadow:none !important;
        padding:0 !important;
        width:240px !important;
    }
    .ftb {
        border-bottom:1px solid #DDD;
        border-left:1px solid #DDD;
        box-sizing:border-box;
        float:left;
        padding:22px 10px 8px 10px;
        width: 50%;
    }
    .ftb:hover {
        cursor:text;
    }
    .ftb:hover i, .ftb:hover input {
        color:#EF3546;
    }
    .ftb.full {
        width: 100%;
    }
    .ftb.full .nothing-txt {
        width:540px !important;
    }
    .ftbp {
        padding-left:12px;
    }
    .ftbp select {
        background:#FFF;
        height:30px;
        margin:0;
        padding:0 8px;
    }
    .ftbp i {
        margin-right: 8px;
    }


    .ftb .top-c {
        color:#CCC;
        display: none;
        font-size:9px;
        left:46px;
        position: absolute;
        top:10px;
    }
</style>
<script type="text/javascript">
    (function($) {
        $('.ftb').click(function() {
            var $this = $(this).closest('.ftb');
            var txt = $this.find('.nothing-txt');
            if (txt.length) {
                txt.focus();
            }

        });

        $('.ftb .nothing-txt').keyup(function() {
            switchTopC();
        });

        function switchTopC() {
            var DURA = 200;
            $.each($('.ftb'), function() {
                var $this = $(this).closest('.ftb');
                var top_c = $this.find('.top-c');
                var input = $this.find('.nothing-txt');
                if (top_c.length && input.length) {
                    top_c.html(input.attr('placeholder'));
                    if (input.val()) {
                        top_c.fadeIn(DURA);
                    } else {
                        top_c.fadeOut(DURA);
                    }
                }
            });

        }
    })(jQuery);
</script>
