<?php
$model = $this->model;
?>

<style>
<?php
if ($model->css) {
    if ($model->css['backgroundcolor']) {
        ?>
            .content {
                background-color:<?php echo $model->css['backgroundcolor']; ?>;
            }
        <?php
    }
    if ($model->css['fontcolor']) {
        ?>
            #product-sub-title, #product-title, #product-brand span {
                color:<?php echo $model->css['fontcolor']; ?>;
            }
        <?php
    }
    if ($model->css['linkcolor']) {
        ?>
            #breadcrumb li a, #product-brand a {
                color:<?php echo $model->css['linkcolor']; ?> !important;
            }
        <?php
    }
    if ($model->css['pricecolor']) {
        ?>
            #product-purc span {
                color:<?php echo $model->css['pricecolor']; ?> !important;
            }
        <?php
    }
    if ($model->css['buttoncolor']) {
        ?>
            #add-to-cart {
                background-color:<?php echo $model->css['buttoncolor']; ?> !important;
            }
            #product-sg .s-img-wp.selected {
                border-color:<?php echo $model->css['buttoncolor']; ?> !important;
            }
        <?php
    }
}
?>
</style>


<div class="content">
    <div class="container_24">

        <div id="product-pg" class="grid_14">
            <?php if (count($model->photo) > 1): ?>
                <?php
                $path = $this->photoImage($model->photo[0]->name . $model->photo[0]->type, 'large');
                ?>
                <button class="lt-arr-btn"></button>
                <button class="rt-arr-btn"></button>
            <?php endif; ?>
            <?php if (count($model->photo)): ?>
                <?php
                $path = $this->photoImage($model->photo[0]->name . $model->photo[0]->type, 'large');
                ?>
                <a href="javascript:void(0)" id="big-photo-link" class="clearfix">
                    <img class="big-photo" src="<?php echo $path ?>"/>
                </a>
            <?php endif; ?>
            <div class="clear"></div>

        </div>

        <div class="grid_10">
            <div class="lpad-30">
                <ul id="breadcrumb" class="clearfix">
                    <li>
                        <a href="/">HOME</a>
                    </li>
                    <?php if ($model->category) : ?>
                        <?php if ($model->category->parent): ?>
                            <li>
                                <i class="ico"></i>
                                <a href="#"><?php echo strtoupper($model->category->parent->name); ?></a>
                            </li>
                        <?php endif; ?>
                        <li>
                            <i class="ico"></i>
                            <a href="#"><?php echo strtoupper($model->category->name); ?></a>
                        </li>
                    <?php endif; ?>

                </ul>

                <h1 id="product-title"><?php echo $model->title ?></h1>
                <?php if ($model->brand): ?>
                    <h2 id="product-brand" class="clearfix"><span>by</span><a href="#" class="bold"><?php echo strtoupper($model->brand->name) ?></a><img src="/img/rockpapa.png" id="product-brand-logo"/></h2>
                <?php endif; ?>
                <?php if ($model->sub_title): ?>
                    <p id="product-sub-title">
                        <?php echo $model->sub_title; ?>
                    </p>
                <?php endif; ?>

                <div id="product-purc" class="clearfix">
                    <div>
                        <span class="symbol">$</span>
                        <span class="price-int">39</span>
                        <span class="price-dec">.95</span>
                        <span class="price-currency">usd</span>
                    </div>
                </div>

                <div id="product-buy" class="clearfix">
                    <div id="set-qty">
                        <button id="sub-btn"></button>
                        <input type="text" id="qty" maxlength="2" value="1"/>
                        <button id="add-btn"></button>
                    </div>

                    <button id="add-to-cart">
                        <i class="ico"></i>Add To Cart
                    </button>
                </div>
                <?php if (count($model->photo)): ?>
                    <div id="product-sg">
                        <?php foreach ($model->photo as $p): ?>
                            <?php
                            $path = $this->photoImage($p->name . $p->type, 'small');
                            ?>
                            <div class='s-img-wp'>
                                <img class="s-img" src="<?php echo $path ?>"/>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div style="height:1000px;">

</div>
<script type="text/javascript">
    (function($) {
        $('.big-photo').xCenter();
        var qty = $('#qty');
        qty.integerInput();
        var minus = $('#sub-btn');
        minus.bind('click', function() {
            var val = parseInt(qty.val());
            if (typeof val === 'number' && !isNaN(val)) {
                val = val - 1;
                if (val == 0) {
                    val = 1;
                }
                qty.val(val);
            } else {
                qty.val(1);
            }
        });
        var plus = $('#add-btn');
        plus.bind('click', function() {
            var val = parseInt(qty.val());
            if (typeof val === 'number' && !isNaN(val)) {
                val = val + 1;
                qty.val(val);
            } else {
                qty.val(1);
            }
        });

        // set gallary selected
        var s_img = $('.s-img-wp');
        if (s_img.length > 0) {
            $(s_img[0]).addClass('selected')
        }


    })(jQuery);
</script>
