<?php
    $logo = $this->company->logo;
    $images = $this->company->images;
    $company = $this->company;
    $wait_tobe_validate = $company->wait_tobe_validate;
    


// 页面所否锁定
    $lock = false;
    if($wait_tobe_validate) {
        $lock = true;
    } else if ($company->validated_bln) {
        $lock = true;
    }
    
    // 是否显示提示框
    $reason_count = count($company->validation_refused_reason);
    $showTip = true;
    $tipType = '';
    if($company->validated_bln) {
        $tipType = 'activated';
    } else {
        if($wait_tobe_validate) {
            $tipType = 'processing';
        } else {
            if($reason_count > 0) {
                $tipType = 'refused';
            } else {
                $showTip = false;
            }
        }
    }
    
    
?>
<div class="container_24 main">
    <div class="grid_18 board relative">
        
        <?php
        if($showTip) {
        ?>
        <div class="shadowbox45degree radiusall_4px toptip">
            <?php
            switch($tipType) {
                case "activated" :
                    ?>
                    <p class="green bold">公司<?php echo $company->name?>已经通过信息认证，所有公司信息均以你提交认证时填写的内容为准，不可更改</p>
            <?php
                    break;
                case "processing" :
                    ?>
                    <p class="red bold">公司<?php echo $company->name?>信息正在审核中，并且该页面不可修改。</p><p style="margin-top:4px">我们会尽快完成审核工作并且第一时间通知你，感谢你的耐心等待</p>
            <?php
                    break;
                case "refused" :
                    ?>
                    <span class="red bold">很抱歉，</span><span>你最近提交的实名认证已被拒绝通过，以下是拒绝的原因，请修正后重新提交，谢谢理解</span>
                    <div class="clear_5px"></div>
                    <p><?php echo $company->validation_refused_reason[$reason_count - 1]->content ?></p>
            <?php
                    break;
                default:
                    break;
            }

            ?>
        </div>
        <?php
        }
        ?>
        
        <div class="infoblock">
            <h1 class="pagetitle" id='baseinfo'>
            公司认证 - 公司基本信息 （公开信息）
            </h1>

            <table class="submittable">
                <tr>
                    <td class="col1">公司全称 <span class="red font12px">*</span></td>
                    <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" value="<?php echo $company->name ?>" id="name" class="ntext"/></td>
                </tr>
                <tr>
                    <td>公司LOGO <span class="red font12px">*</span></td>
                    <td>
                        <div id="companyphoto" style="background-image:url(<?php echo $this->logoUrl ?>)" class="shadowbox"><?php if(!$lock){ ?><input class="editcompanyphoto btn btn_white gbtnnoicon" id="editcompanyphoto" type="button" value="编辑图片"/><?php } ?></div>
                        <input type="hidden" requiredfield="yes" for="companyphoto" id="companyphotouploaded" class="uploadInput" value="<?php if(isset($logo)){echo '1';} else { echo '0'; }?>"/>
                    </td>
                </tr>
                <!--IMAGES-->
                <tr class="fileattached">
                    <td class="col1">公司图片 <span class="red font12px">*</span></td>
                    <td>
                        <?php if(!$lock){ ?><input type="button" class="btn_white" id="images" fieldname="images" value="添加图片..." /><?php } ?>
                        <div class="uploadedwrapper" model="multi" for="images" id="imagesuploaded">
                            <?php
                            $hiddenValue = "0";
                            foreach($images as $img) {
                                $url = $this->companyImage($img->angelname, 'medium');
                                $originUrl = $this->companyImage($img->angelname, 'orig');  
                                $hiddenValue = "1";
                            ?>
                            <div class="image fileitem">
                                <a target='_blank' href="<?php echo $originUrl; ?>"><img src="<?php echo $url ?>"/></a>
                                <?php if(!$lock){ ?><span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-image')?>', '', '<?php echo $company->id ?>', '<?php echo $img->id ?>')" class='delete'></span><?php } ?>
                            </div>

                            <?php
                            }
                            ?>

                            <input type="hidden" value="<?php echo $hiddenValue; ?>" requiredfield="yes" class="uploadInput" for="images">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>公司视频链接</td>
                    <td class="relative">
                        <div class="relative">
                            <textarea id="company_video" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="ntext narea"><?php echo $company->company_video ?></textarea>
                            <a href="javascript:void(0)" title="预览效果" class="videoplaybtn"></a>
                        </div>
                        
                    </td>
                </tr>
                <tr>
                        <td>投资人附加权益</td>
                        <td>
                            <textarea id="additional_rights" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="ntext narea"><?php echo $company->additional_rights ?></textarea>
                        </td>
                </tr>
                <tr>
                        <td>用一句话描述产品或服务 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="brief_descr" value="<?php echo $company->brief_descr ?>" class="ntext" maxlength="20"/></td>
                </tr>
                <tr>
                        <td>项目亮点 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="highlight" value="<?php echo $company->highlight ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>怎样赚钱 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="profit_model" value="<?php echo $company->profit_model ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>为什么是我、竞争优势 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="advantage" value="<?php echo $company->advantage ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>600字业务介绍 <span class="red font12px">*</span></td>
                        <td><textarea id="descr" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" class="ntext narea" maxlength="600"><?php echo $company->descr ?></textarea></td>
                </tr>
                <tr>
                        <td>发展历史和规划 <span class="red font12px">*</span></td>
                        <td><textarea id="history" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" class="ntext narea"><?php echo $company->history ?></textarea></td>
                </tr>
                <tr>
                        <td>法人代表 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="representative" value="<?php echo $company->representative ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>公司成立时间 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="founded_date" value="<?php echo $company->founded_date ?>" class="ntext"/></td>
                </tr>
                <tr class="scale">
                        <td>公司规模 <span class="red font12px">*</span></td>
                        <td>
                            <?php $size = $company->size; if(!isset($size)) { $size = 0;} ?>
                            <select id="size" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes">
                                <option value="0" <?php if($size == 0) echo "selected='selected'"; ?> >请选择</option>
                                <option value="10" <?php if($size == 10) echo "selected='selected'"; ?> >5-10人</option>
                                <option value="50" <?php if($size == 50) echo "selected='selected'"; ?> >11-50人</option>
                                <option value="100" <?php if($size == 100) echo "selected='selected'"; ?> >51-100人</option>
                                <option value="500" <?php if($size == 500) echo "selected='selected'"; ?> >101-500人</option>
                                <option value="1000" <?php if($size == 1000) echo "selected='selected'"; ?> >501-1000人</option>
                                <option value="1001" <?php if($size == 1001) echo "selected='selected'"; ?> >1000人以上</option>
                            </select>
                        </td>
                </tr>
                <tr>
                        <td>公司网站链接 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="website" value="<?php echo $company->website ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>公司电话 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="phone" value="<?php echo $company->phone ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>公司地址 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="address" value="<?php echo $company->address ?>" class="ntext"/></td>
                </tr>
                <tr>
                        <td>公司传真 <span class="red font12px">*</span></td>
                        <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="fax" value="<?php echo $company->fax ?>" class="ntext"/></td>
                </tr>
            </table>

            <div class="clear_50px"></div>
        </div>
        <div class="infoblock">
            <h1 class="pagetitle" id='readme'>
            创业者自述
            </h1>

            <table class="submittable">
                <tr>
                    <td class="col1">视频链接 <span class="red font12px">*</span></td>
                    <td class="relative">
                        <textarea requiredfield="yes" <?php if($lock){ ?>disabled="disabled"<?php } ?> id="startup_introduction_video" class="ntext narea"><?php echo $company->startup_introduction_video ?></textarea>
                        <a href="javascript:void(0)" title="预览效果" class="videoplaybtn"></a>
                    </td>
                </tr>

                <tr>
                    <td>文字描述 <span class="red font12px">*</span></td>
                    <td><textarea id="startup_introduction" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" class="ntext narea"><?php echo $company->startup_introduction ?></textarea></td>
                </tr>
            </table>

            <div class="clear_50px"></div>
        </div>
        <div class="infoblock">
            <h1 class="pagetitle" id='requirement'>
            融资需求 （公开信息）
            </h1>

            <table class="submittable">
                    <tr class="target">
                            <td class="col1">融资目标 <span class="red font12px">*</span></td>
                            <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" value="<?php echo $company->getExpectedFundingAmt() ?>" id="expected_funding_amt" class="ntext integer"/> 万元</td>
                    </tr>
                    <tr class="deadline">
                            <td>目标融资时限 <span class="red font12px">*</span></td>
                            <td>
                                <?php $funding_period = $company->funding_period; if(!isset($funding_period)) { $funding_period = 0;} ?>
                                <select id="funding_period" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes">
                                    <option value="0" <?php if($funding_period == 0) echo "selected='selected'"; ?> >请选择</option>
                                    <option value="30" <?php if($funding_period == 30) echo "selected='selected'"; ?> >30天</option>
                                    <option value="60" <?php if($funding_period == 60) echo "selected='selected'"; ?> >60天</option>
                                    <option value="90" <?php if($funding_period == 90) echo "selected='selected'"; ?> >90天</option>
                                    <option value="120" <?php if($funding_period == 120) echo "selected='selected'"; ?> >120天</option>
                                </select>
                            </td>
                    </tr>
                    <tr class="stock">
                            <td>目标融资金额出售股份 <span class="red font12px">*</span></td>
                            <td><input type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> requiredfield="yes" id="funding_stock_percent" value="<?php echo $company->funding_stock_percent ?>" class="ntext integer"/> %</td>
                    </tr>
                    <tr class="stockprice">
                            <td>最小投资单位 <span class="red font12px">*</span></td>
                            <td>
                                <div class="relative"><span class="fixthousand">000</span><input  type="text" <?php if($lock){ ?>disabled="disabled"<?php } ?> id="funding_mini_unit" requiredfield="yes" value="<?php echo $company->getFundingMiniUnit() ?>" style="padding-right:58px;width:30px;text-align:right;" class="ntext integer"/> 元</div>
                                
                                <label class="gray font12px">等价于 <span id="funding_mini_unit_perc"></span>%股份</label>
                            </td>
                    </tr>

            </table>
            <div class="signblock radiusall_4px">
                融资条款 <span class="red bold">*</span> &nbsp;
                <input type="button" id="sign_raising_term" class="btn btn_white gbtnnoicon" value="阅读并签署"/>
<!--                <input type="hidden" for="sign_raising_term" value="0" requiredfield="yes"/>-->
            </div>
            <div class="clear_50px"></div>
        </div>
        <div class="infoblock">
            <h1 class="pagetitle" id='docs'>
            融资文档 （非公开信息）
            </h1>

            <table class="submittable">
                <!--FFS-->
                <tr class="fileattached">
                    <td class="col1">融资需求计划书 <span class="red font12px">*</span></td>
                    <td>
                        
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="ffs" fieldname="funding_specification" value="添加文件（多文件）..." />
                        <div class="uploadedwrapper" for="ffs" model="multi" id="ffsuploaded">
                            <?php
                                $funding_specification_count = count($company->funding_specification);
                                $hiddenValue = 0;
                                if($funding_specification_count > 0){
                                    $hiddenValue = 1;
                                    for($i = 0;$i < $funding_specification_count; $i++) {
                                        $funding_specification = $company->funding_specification[$i];
                                        if(!$funding_specification->active_bln) {
                                            continue;
                                        }
                                        $ffsUrl = $this->url(array('doctype'=>$this->type_fund_spec, 'company_id'=>$company->id, 'doc_id'=>$funding_specification->id), 'company-doc');
                            ?>
                            <p class='fileitem attachfile'><a href="<?php echo $ffsUrl ?>"><?php echo $funding_specification->filename ?></a>
                                <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_fund_spec ?>', '<?php echo $company->id ?>', '<?php echo $funding_specification->id ?>')" class='delete'></span>
                            </p>
                            <?php
                                    }
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue ?>" requiredfield="yes" class="uploadInput" for="ffs">
                        </div>
                    </td>
                </tr>
                <!--FBL-->
                <tr>
                    <td>营业执照 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="fbl" fieldname="business_licence" value="选择文件（单文件）..." />
                        <div class="uploadedwrapper" for="fbl" id="fbluploaded">
                            
                            <?php
                            $hiddenValue = 0;
                            if($company->business_licence->active_bln){
                                $fblUrl = $this->url(array('doctype'=>$this->type_business_licence, 'company_id'=>$company->id, 'doc_id'=>$company->business_licence->id), 'company-doc');
                                $hiddenValue = 1;
                            ?>
                                <p class='fileitem attachfile'>
                                    <a href="<?php echo $fblUrl ?>"><?php echo $company->business_licence->filename ?></a>
                                    <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_business_licence ?>', '<?php echo $company->id ?>', '<?php echo $company->business_licence->id ?>')" class='delete'></span>
                                </p>
                            <?php
                                }
                            ?>
                            
                            <input type="hidden" value="<?php echo $hiddenValue ?>" requiredfield="yes" class="uploadInput" for="fbl">
                            
                        </div>
                    </td>
                </tr>
                <!--FFUS-->
                <tr>
                    <td>公司现有股东组成情况证明 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="ffus" fieldname="funder_specification" value="选择文件（单文件）..." />
                        <div class="uploadedwrapper" for="ffus" id="ffusuploaded">
                            
                            
                            <?php
                            $hiddenValue = 0;
                            if($company->funder_specification->active_bln){
                                $ffusUrl = $this->url(array('doctype'=>$this->type_funder_spec, 'company_id'=>$company->id, 'doc_id'=>$company->funder_specification->id), 'company-doc');
                                $hiddenValue = 1;
                            ?>
                                <p class='fileitem attachfile'>
                                    <a href="<?php echo $ffusUrl ?>"><?php echo $company->funder_specification->filename ?></a>
                                    <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_funder_spec ?>', '<?php echo $company->id ?>', '<?php echo $company->funder_specification->id ?>')" class='delete'></span>
                                </p>
                            <?php
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue?>" requiredfield="yes" class="uploadInput" for="ffus"/>
                        </div>
                    </td>
                </tr>
                <!--FFD-->
                <tr>
                    <td>股东会决议 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="ffd" fieldname="funder_decision" value="选择文件（单文件）..." />
                        <div class="uploadedwrapper" for="ffd" id="ffduploaded">
                            <?php
                            $hiddenValue = 0;
                            if($company->funder_decision->active_bln){
                                $hiddenValue = 1;
                                $ffdUrl = $this->url(array('doctype'=>$this->type_funder_decision, 'company_id'=>$company->id, 'doc_id'=>$company->funder_decision->id), 'company-doc');
                            ?>
                                <p class='fileitem attachfile'>
                                    <a href="<?php echo $ffdUrl ?>"><?php echo $company->funder_decision->filename ?></a>
                                    <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_funder_decision ?>', '<?php echo $company->id ?>', '<?php echo $company->funder_decision->id ?>')" class='delete'></span>
                                </p>
                            <?php
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue?>" requiredfield="yes" class="uploadInput" for="ffd">
                        </div>
                    </td>
                </tr>
                <!--FCR-->
                <tr>
                    <td>公司信用报告 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="fcr" fieldname="credit_reports" value="添加文件（多文件）..." />
                        <div class="uploadedwrapper" for="fcr" model="multi" id="fcruploaded">
                            
                            <?php
                                $hiddenValue = 0;
                                $credit_reports_count = count($company->credit_reports);
                                if($credit_reports_count > 0){
                                    $hiddenValue = 1;
                                    for($i = 0;$i < $credit_reports_count; $i++) {
                                        $credit_reports = $company->credit_reports[$i];
                                        if(!$credit_reports->active_bln) {
                                            continue;
                                        }
                                        $fcrUrl = $this->url(array('doctype'=>$this->type_credit_report, 
                                            'company_id'=>$company->id, 
                                            'doc_id'=>$credit_reports->id), 
                                            'company-doc');
                            ?>
                            <p class='fileitem attachfile'>
                                <a href="<?php echo $fcrUrl ?>"><?php echo $credit_reports->filename ?></a>
                                <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_credit_report ?>', '<?php echo $company->id ?>', '<?php echo $credit_reports->id ?>')" class='delete'></span>
                            </p>
                            <?php
                                    }
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue?>" requiredfield="yes" class="uploadInput" for="fcr">
                        </div>
                    </td>
                </tr>
                <!-- FPCR -->
                <tr>
                    <td>融资人信用报告 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="fpcr" fieldname="personal_credit_reports" value="添加文件（多文件）..." />
                        <div class="uploadedwrapper" for="fpcr" model="multi" id="fpcruploaded">
                            
                            <?php
                                $hiddenValue = 0;
                                $personal_credit_reports_count = count($company->personal_credit_reports);

                                if($personal_credit_reports_count > 0){
                                    $hiddenValue = 1;
                                    for($i = 0;$i < $personal_credit_reports_count; $i++) {
                                        $personal_credit_reports = $company->personal_credit_reports[$i];
                                        if(!$personal_credit_reports->active_bln) {
                                            continue;
                                        }

                                        $fpcrUrl = $this->url(array('doctype'=>$this->type_personal_credit_report, 
                                            'company_id'=>$company->id, 
                                            'doc_id'=>$personal_credit_reports->id), 
                                            'company-doc');

                            ?>
                            <p class='fileitem attachfile'>
                                <a href="<?php echo $fpcrUrl ?>"><?php echo $personal_credit_reports->filename ?></a>
                                <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_personal_credit_report ?>', '<?php echo $company->id ?>', '<?php echo $personal_credit_reports->id ?>')" class='delete'></span>
                            </p>
                            <?php
                                    }
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue?>" requiredfield="yes" class="uploadInput" for="fpcr">
                        </div>
                    </td>
                </tr>
                <!-- FPCR -->
                <!--FFR-->
                <tr>
                    <td>财务报表 <span class="red font12px">*</span></td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="ffr" fieldname="financial_reports" value="添加文件（多文件）..." />
                        <div class="uploadedwrapper" for="ffr" model="multi" id="ffruploaded">
                            
                            <?php
                                $hiddenValue = 0;
                                $financial_reports_count = count($company->financial_reports);
                                if($financial_reports_count > 0){
                                    $hiddenValue = 1;
                                    for($i = 0;$i < $financial_reports_count; $i++) {
                                        $financial_reports = $company->financial_reports[$i];
                                        if(!$financial_reports->active_bln) {
                                            continue;
                                        }
                                        $ffrUrl = $this->url(array('doctype'=>$this->type_financial_report, 
                                            'company_id'=>$company->id, 
                                            'doc_id'=>$financial_reports->id), 
                                            'company-doc');
                            ?>          
                            <p class='fileitem attachfile'>
                                <a href="<?php echo $ffrUrl ?>"><?php echo $financial_reports->filename ?></a>
                                <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_financial_report ?>', '<?php echo $company->id ?>', '<?php echo $financial_reports->id ?>')" class='delete'></span>
                            </p>
                            <?php
                                    }
                                }
                            ?>
                            <input type="hidden" value="<?php echo $hiddenValue?>" requiredfield="yes" class="uploadInput" for="ffr">
                        </div>
                    </td>
                </tr>
                <!--FSF-->
                <tr>
                    <td>其他支持文件</td>
                    <td>
                        <input type="button" <?php if($lock){ ?>disabled="disabled"<?php } ?> class="btn_white company_doc" id="fsf" fieldname="support_files" value="添加文件（多文件）..." />
                        <div class="uploadedwrapper" for="fsf" model="multi" id="fsfuploaded">
                            <?php
                                $support_files_count = count($company->support_files);
                                if($support_files_count > 0){

                                    for($i = 0;$i < $support_files_count; $i++) {
                                        $support_files = $company->support_files[$i];
                                        if(!$support_files->active_bln) {
                                            continue;
                                        }
                                        $fsfUrl = $this->url(array('doctype'=>$this->type_support_files, 
                                            'company_id'=>$company->id, 
                                            'doc_id'=>$support_files->id), 
                                            'company-doc');
                            ?>
                            <p class='fileitem attachfile'>
                                <a href="<?php echo $fsfUrl ?>"><?php echo $support_files->filename ?></a>
                                <span onclick="deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc')?>', '<?php echo $this->type_support_files ?>', '<?php echo $company->id ?>', '<?php echo $support_files->id ?>')" class='delete'></span>
                            </p>
                            <?php
                                    }
                                }
                            ?>
                        </div>
                    </td>
                </tr>
                
            </table>

            <div class="clear_50px"></div>
        </div>
        <div class="infoblock">
            <h1 class="pagetitle" id='guarantees'>
                    担保人
            </h1>
            <strong id="guarantee_candidate">必须填写三位担保人</strong><div class="clear_10px"></div>
            <input type="hidden" id="guarantees_hid" for="guarantee_candidate" requiredfield='yes' value=""/>
            <div class="addedguarantees">
                
            </div>
        </div>
        <div class="clear_50px"></div>
        <div class="boldline nomargin"></div>
        <div class="clear_20px"></div>
        <div class="signblock radiusall_4px">
            融资协议 <span class="red bold">*</span> &nbsp;
            <input type="button" id="sign_raising_agreement" class="btn btn_white gbtnnoicon btn_white_disabled" disabled="disabled" value="阅读并签署"/>
            <input type="hidden" value="0" for="sign_raising_agreement" requiredfield="yes"/>
        </div>
        <div class="clear_20px"></div>
        <?php if(!$lock){ ?>
        <input type="button" value="填写完毕，提交公司认证申请" id="submitbtn" class="btn"/>
        <?php } ?>
    </div>

    <div class="grid_6">
        <div class="clear_80px"></div>
        <div id="sidenavwrapper">
            <ul class="sidenav">
                <li class='sidenavli selected' for='baseinfo'>
                    <a href="javascript:void(0)">
                            公司基本信息
                    </a>
                </li>
                <li class='sidenavli' for='readme'>
                    <a href="javascript:void(0)">
                            创业者自述
                    </a>
                </li>
                <li class='sidenavli' for='requirement'>
                    <a href="javascript:void(0)">
                            融资需求
                    </a>
                </li>
                <li class='sidenavli' for='docs'>
                    <a href="javascript:void(0)">
                            融资文档（非公开信息）
                    </a>
                </li>
                <li class='sidenavli' for='guarantees'>
                    <a href="javascript:void(0)">
                            添加担保人
                    </a>
                </li>
            </ul>
        </div>
        <div class="clear_50px"></div>
    </div>
</div>
<iframe id="thumbnail-upload-iframe" src="<?php echo $this->url(array('company_id'=>$this->id), 'company-thumbnail'); ?>" class="hidden"></iframe>
<iframe id="company-image-upload-iframe" src="<?php echo $this->url(array('company_id'=>$this->id), 'upload-company-image'); ?>" class="hidden"></iframe>
<iframe id="company-doc-upload-iframe" src="<?php echo $this->url(array('company_id'=>$this->id), 'upload-company-doc'); ?>" class="hidden"></iframe>

<div id="loaderdivwrapper" class="hidden">
    <div class="loaderdiv"></div>
</div>

<div id="failpopupwrapper_companydoc" class="hidden">
    <div class="failpopup" style="background:url('http://cdn1.iconfinder.com/data/icons/function_icon_set/cancel_48.png') 20px 20px no-repeat;padding:20px;padding-left:80px;">
        <p class="bold">文件上传失败！请检查后重试:</p>
        <ul class="leftmargin20px">
            <li>文件的大小不能超过了10M</li>
            <li>网络传输故障</li>
        </ul>
    </div>
</div>
<div id="failpopupwrapper" class="hidden">
    <div class="failpopup" style="background:url('http://cdn1.iconfinder.com/data/icons/function_icon_set/cancel_48.png') 20px 20px no-repeat;padding:20px;padding-left:80px;">
        <p class="bold">LOGO上传失败！请检查后重试:</p>
        <ul class="leftmargin20px">
            <li>图片的大小不能超过了5M</li>
            <li>图片的格式必须为JPG或PNG</li>
        </ul>
    </div>
</div>

<div class="hidden" id="thumbnail-crop-modal">
    <div class="thumbnail-crop-wrapper paddingbox20px">
        <div class="lt thumbnail-crop-image">
            <img id="img-thumbnail" />
        </div>
        <div class="rt">
            <div class="block">
                <div class="thumbnail thumbnail-180 overflow-hidden">
                    <img id="thumbnail-180"/>
                </div>
                <div>
                    <div>中尺寸LOGO</div>
                    <span class="label">180 * 180 像素</span>
                </div>
            </div>
            
            <div class="block">
                <div class="thumbnail thumbnail-50 overflow-hidden">
                    <img id="thumbnail-50"/>
                </div>
                <div>
                    <div>小尺寸LOGO</div>
                    <span class="label">50 * 50 像素</span>
                </div>
            </div>
        </div>
    </div>
    <div class="thumbnail-crop-footer">
        <input type="button" class="btn" id="btn-finish-crop" value="完成裁剪"/>
    </div>
</div>

<div class="hidden" id="law_panel_term">
    <div class="paddingbox20px law_panel">
        <p>以下为<strong id="law_panel_term_company_id"></strong>公司借贷及债转股协议的主要条款：</p>
        <table>
            <tr>
                <td class="col1"><strong>借贷金额:</strong></td>
                <td>借贷金额总计人民币<strong class="inputfield" id="law_panel_term_amount"></strong>元</td>
            </tr>
            <tr>
                <td><strong>贷方:</strong></td>
                <td><strong class="inputfield" id="law_panel_term_lender"></strong></td>
            </tr>
            <tr>
                <td><strong>借贷期限:</strong></td>
                <td>自借贷完成之日起 5 年</td>
            </tr>
            <tr>
                <td><strong>利息:</strong></td>
                <td>单利为应付贷款额的 3 % ； 借贷期限到期时支付利息；如果债转成股则免除利息</td>
            </tr>
            <tr>
                <td><strong>债转股条件:</strong></td>
                <td>在借贷期限以内，当公司发生下一轮融资且融资金额不低于人民币 20 万元时，该债务自动转为股份。或由贷方选择可在任何时刻转为股份。</td>
            </tr>
            <tr>
                <td><strong>转股价格:</strong></td>
                <td>借贷金额以投资前估值人民币<strong id="law_panel_term_company_total"></strong>元</td>
            </tr>
            <tr>
                <td><strong>转换所得股份:</strong></td>
                <td>根据以上借贷金额和转股价格，如果发生债转股，贷方将获得公司的<strong class="inputfield" id="law_panel_term_company_stock"></strong>股份。</td>
            </tr>
            <tr>
                <td><strong>费用:</strong></td>
                <td>各方承担在债转股中各自所需费用。</td>
            </tr>
        </table>
        <p>以上条款仅代表双方借贷和转股所达成的共识和意愿，不具备法律效力。</p>
        <p>详细法律条款见《债转股合同》。</p>
        <p>借贷完成时间以借贷款实际转出为准。</p>
        <table class="signtable">
            <tr>
                <td class="bold">借方</td><td></td>
            </tr>
            <tr>
                <td>&nbsp;<span id="law_panel_representative"></span></td><td>日期 &nbsp;<span id="law_panel_today"></span></td>
            </tr>
            <tr>
                <td class="bold">贷方</td><td></td>
            </tr>
            <tr>
                <td><span class="inputfield"></span></td><td>日期<span class="inputfield"></span></td>
            </tr>
        </table>
        <p>* 所有下划线标识的部分将由贷方提供的内容填充</p>
    </div>
</div>

<?php if(!$lock) { ?>
<div id="ag" class="hidden">
    <div class="addguarantee vg">
        <div class="body">
            <table>
                <tr>
                    <td class="col1">
                        担保人姓名
                    </td>
                    <td>
                        <input type="text" class="text vname"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        与担保人关系
                    </td>
                    <td>
                        <input type="text" class="text vrelationship"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        担保人邮箱
                    </td>
                    <td>
                        <input type="text" class="text vemail"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        担保人联系电话
                    </td>
                    <td>
                        <input type="text" class="text vphone"/>
                    </td>
                </tr>
            </table>
        </div>
        <div class="footer">
            <input type="button" id="addguaranteebtn" class="btn btn_white gbtnnoicon" value="添加担保人"/>
        </div>
    </div>
</div>

<div id="eg" class="hidden">
    <div class="editguarantee vg" gid="">
        <div class="body">
            <table>
                <tr>
                    <td class="col1">
                        担保人姓名
                    </td>
                    <td>
                        <input type="text" class="text vname"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        与担保人关系
                    </td>
                    <td>
                        <input type="text" class="text vrelationship"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        担保人邮箱
                    </td>
                    <td>
                        <input type="text" class="text vemail"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        担保人联系电话
                    </td>
                    <td>
                        <input type="text" class="text vphone"/>
                    </td>
                </tr>
            </table>
        </div>
        <div class="footer">
            <input type="button" id="editguaranteebtn" class="btn btn_white gbtnnoicon" value="编辑担保人"/>
        </div>
    </div>
</div>
<?php
}
?>
<div class="toaddg questionbg hidden"></div>

<div gid="" class="addedg questionbg hidden">
    姓名：<strong class="name"></strong><br>
    关系：<span class="relationship"></span><br>
    邮箱：<span class="email"></span><br>
    电话：<span class="phone"></span>
    <?php if(!$lock) { ?><a class="edit" href="javascript:void(0)"></a><?php } ?>
</div>


<div class="hidden" id="law_panel_agreement">
    <div class="paddingbox20px">
        
    </div>
</div>

<div class="hidden" id="video_show_panel">
    
</div>

<link rel="stylesheet" type="text/css" href="<?php echo $this->cssPath("jquery.Jcrop.min.css"); ?>" />
<script type="text/javascript" src="<?php echo $this->jsPath('jquery.Jcrop.min.js'); ?>"></script>
<script type="text/javascript">
    (function($){
        $('body').addClass('loginpage');
        $('body').addClass('companyinfo');
    })(jQuery);
</script>

<script type="text/javascript">
    (function($){
        var companyId = '<?php echo $this->id; ?>';
        var useremail = '<?php echo $this->me->getUser()->email ?>';
        $('#images').inputTip('至少请上传一张图片','mouseenter','mouseleave',70);
        var ffdContent = "<p class='multrowblock'>经全体股东签字的股东会决议扫描件。全体股东一致同意公司与深圳天使圈信息技术有限公司签署的《融资协议》中的所有规定，包括其中涉及期权授予和股权转让的相关规定。</p><div class='middleline'></div><p> 请点击下载 <a href='javascript:void(0)' class='yellow'>《股东会决议模版》</a></p>";
        $('#ffd').inputTip(ffdContent,'mouseover','mouseout',70);
        var ffusContent = "<p class='multrowblock'>当地工商部门出具的证明扫描件，列明每位股东姓名及各自所占比例（如股东张三：70% 股东李四：30%）</p>";
        $('#ffus').inputTip(ffusContent,'mouseover','mouseout',70);
        var fcrContent = "<p>中国人民银行出具的公司信用报告</p><div class='middleline'></div><a href='javascript:void(0)' class='yellow'>如何获取该报告？</a>";
        $('#fcr').inputTip(fcrContent,'mouseenter','mouseleave',70);
        var personalcreditreportContent = "<p>中国人民银行出具的个人信用报告</p><div class='middleline'></div><a href='javascript:void(0)' class='yellow'>如何获取该报告？</a>";
        $('#personalcreditreport').inputTip(personalcreditreportContent,'mouseenter','mouseleave',70);
        $('#fsf').inputTip('例如：专利书，客户合同等','mouseenter','mouseleave',70);
        $('#ffr').inputTip('至少上传一个文档','mouseenter','mouseleave',70);
        $('#fpcr').inputTip('我们仅接受PDF,WORD文档,EXCEL文档,PPT文档','mouseenter','mouseleave',70);
        $('#representative').inputTip('请填写法人的真实姓名','focus','blur',25);
        $('#founded_date').inputTip('请填写公司成立时间','focus','blur',25);
        $('#company_video').inputTip('请填写公司视频网页的嵌套代码','focus','blur',25);
        var brief_descr = "<p>请使用20字以内的一句话描述清楚公司的产品或服务。</p><div class='middleline'></div><a class='yellow' target='_blank' href='http://www.36kr.com/p/73281.html'>创业公司如何用一句话描述清楚自己的产品或服务？</a>";
        $('#brief_descr').inputTip(brief_descr,'focus','blur',25);
        
        
        $('#sidenavwrapper').stickyBox(120);
        $('.sidenav li').click(function(e){
            $('.sidenav .selected').removeClass('selected');
            var object = $(e.target);
            object = findParentByClass(object, 'sidenavli');
            object.addClass('selected');
            var anchorId = object.attr('for');
            var target = $("#" + anchorId);
            var top = target.offset().top;
            $('html, body').animate({ scrollTop: top - 10 }, 300);
        });
        
        
        
        // ************ 右侧滑动菜单
        
        $(window).scroll(function (e) {
            var window = $(e.target);
            var scrollOffset = window.scrollTop();
            $('.infoblock').each(function(i,j){
                var wrapper = $(j);
                var h1 = wrapper.find(".pagetitle");
                var h1Top = h1.offset().top;
                var blockHeight = wrapper.height();
                var blockBottom = h1Top + blockHeight;

                if(scrollOffset >= h1Top - 20 && scrollOffset <= blockBottom) {
                    var id = h1.attr('id');
                    $(".sidenav .selected").removeClass('selected');
                    $(".sidenavli[for='" + id + "']").addClass('selected');
                }
            });
        });
        
        // ************ 公司文件上传
        
        $('.company_doc').click(function(e){
            var object = $(e.target);
            var companyDocUploadIframe = $('#company-doc-upload-iframe');
            var doctype = object.attr('id');
            companyDocUploadIframe.off('load');
            companyDocUploadIframe.on('load', function(){
                $.popupClose();
                object.validResultHide();
                var status = companyDocUploadIframe.contents().find('body input[name="status"]:first').val();
                var offsetObject = getOffset(doctype);
                
                if(status != '1'){
                    var options = {modal:false};
                    $.popup(options, 'failpopupwrapper_companydoc');
                    object.validResultShow('error', "文件上传失败", offsetObject.offset, offsetObject.topOffset);
                }
                else{
                    object.validResultShow('right', '文件上传成功', offsetObject.offset, offsetObject.topOffset);
                    var path = companyDocUploadIframe.contents().find('body input[name="path"]:first').val();
                    var filename = companyDocUploadIframe.contents().find('body input[name="filename"]:first').val();
                    var doc_id = companyDocUploadIframe.contents().find('body input[name="doc_id"]:first').val();
                    var wrapper = $(".uploadedwrapper[for='" + object.attr('id') + "']");
                    var model = wrapper.attr('model');
                    if(model === 'multi') {
                        // multi file uploading
                        // wrapper.append();
                    } else {
                        // single file uploading
                        wrapper.find('.attachfile').remove();
                    }
                    
                    var alink = "<p class='fileitem attachfile'><a href='" + path + "'>" + filename + "</a><span class='delete'  onclick=\"deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-doc') ?>','" + doctype + "','" + companyId + "','" + doc_id + "')\" ></span></p>";
                    wrapper.append(alink);
                    wrapper.find('.uploadInput').val(1);
                    
                    checkAllValid();
                }
                
                $.validResultReset();
            });

            var fileInput = companyDocUploadIframe.contents().find('body input[type="file"]');
            companyDocUploadIframe.contents().find('body input[name="doctype"]').val(doctype);
            var handleFunc = function (){
                var form = companyDocUploadIframe.contents().find('form');
                form.submit();
            };

            var options = {modal:true, event:'change', agpopupframe:false, func:handleFunc};

            // 绑定读取进度条图标
            fileInput.attr('popuptargetid','loaderdivwrapper');
            fileInput.popup(options);
            fileInput.click();
        });
        
        
        // ************ 公司图片上传
        
        $('#images').click(function(e){
            var object = $(e.target);
            
            var companyImageUploadIframe = $('#company-image-upload-iframe');
            //var doctype = $(e.target).attr('id');
            
            companyImageUploadIframe.off('load');
            companyImageUploadIframe.on('load', function(){
                $.popupClose();
                object.validResultHide();
                var offsetObject = getOffset(object.attr('id'));
                var status = companyImageUploadIframe.contents().find('body input[name="status"]:first').val();
                if(status != '1'){
                    var options = {modal:false};
                    $.popup(options, 'failpopupwrapper_companydoc');
                    
                    object.validResultShow('error', "文件上传失败", offsetObject.offset, offsetObject.topOffset);
                }
                else{
                    object.validResultShow('right', '文件上传成功', offsetObject.offset, offsetObject.topOffset);
                    var path = companyImageUploadIframe.contents().find('body input[name="path"]:first').val();
                    var orig = companyImageUploadIframe.contents().find('body input[name="orig"]:first').val();
                    var doc_id = companyImageUploadIframe.contents().find('body input[name="doc_id"]:first').val();
                    var wrapper = $(".uploadedwrapper[for='" + object.attr('id') + "']");
                    wrapper.find('.uploadInput').val(1);
                    var html = "<div class='image fileitem'><a target='_blank' href=" + orig + "><img src=" + path + "></a><span class='delete' onclick=\"deleteUploadedDoc(this, '<?php echo $this->url(array(), 'remove-company-image') ?>','','" + companyId + "','" + doc_id + "')\"></span></div>";
                    wrapper.append(html);
                    
                    checkAllValid();
                }
                
                $.validResultReset();
            });
            
            var fileInput = companyImageUploadIframe.contents().find('body input[type="file"]');
            var handleFunc = function (){
                var form = companyImageUploadIframe.contents().find('form');
                form.submit();
            };
            
            var options = {modal:true, event:'change', agpopupframe:false, func:handleFunc};
            
            // 绑定读取进度条图标
            fileInput.attr('popuptargetid','loaderdivwrapper');
            fileInput.popup(options);
            fileInput.click();
        });
        
        // ************ 编辑用户图片
        
        $('#editcompanyphoto').click(function(){
            var thumbnailUploadIframe = $('#thumbnail-upload-iframe');
            // 获取上传控件
            thumbnailUploadIframe.off('load');
            thumbnailUploadIframe.on('load', function(){
                $.popupClose(0);
                var status = thumbnailUploadIframe.contents().find('body input[name="status"]:first').val();
                if(status != '1'){
                    var options = {modal:false};
                    $.popup(options, 'failpopupwrapper');
                }
                else{
                    var path = thumbnailUploadIframe.contents().find('body input[name="path"]:first').val();
                    winCrop.loadImg(path);
                }
            });
            
            var fileInput = thumbnailUploadIframe.contents().find('body input[type="file"]');
            var handleFunc = function (){
                var form = thumbnailUploadIframe.contents().find('form');
                form.submit();
            };
            
            var options = {modal:true, event:'change', agpopupframe:false, func:handleFunc};
            // 绑定读取进度条图标
            fileInput.attr('popuptargetid','loaderdivwrapper');
            fileInput.popup(options);
            fileInput.click();
        });
        
        var winCrop = {
            jcrop_api: null,
            coords:{x:100, y:100, w:180, h:180},
            loadImg: function(imgPath){
                
                var options = {title:'修改裁剪公司logo', speed:0};
                $.popup(options, 'thumbnail-crop-modal');
                $('#img-thumbnail').attr('src', imgPath);
                $('#thumbnail-180').attr('src', imgPath);
                $('#thumbnail-50').attr('src', imgPath);
                
            },
            showPreview: function(){
                var self = this;
                return function(coords){
                    self.coords = coords;
                    var rx = 180 / coords.w;
                    var ry = 180 / coords.h;

                    $('#thumbnail-180').css({
                            width: Math.round(rx * 540) + 'px',
                            height: Math.round(ry * 400) + 'px',
                            marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                            marginTop: '-' + Math.round(ry * coords.y) + 'px'
                    });

                    rx = 50 / coords.w;
                    ry = 50 / coords.h;
                    $('#thumbnail-50').css({
                            width: Math.round(rx * 540) + 'px',
                            height: Math.round(ry * 400) + 'px',
                            marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                            marginTop: '-' + Math.round(ry * coords.y) + 'px'
                    });
                }
            },
            setSelect: function(){
                this.jcrop_api.setSelect(this.coords);
            },
            finishCrop: function(){
                var self = this;
                return function(){
                    $('#btn-finish-crop').processBtn('正在裁剪...');
                    
                    $.post('<?php echo $this->url(array('company_id'=>$this->id), 'crop-company-logo')?>', self.coords, function(response){
                        var targetId = "companyphoto";
                        $('#' + targetId).css('background-image', 'url(' + response.image + ")");
                        $('#companyphotouploaded').val(1);
                        self.jcrop_api.destroy();
                        $.popupClose();
                        var offsetObj = getOffset(targetId);
                        $('#' + targetId).validResultShow('right','图片已保存',offsetObj.offset,offsetObj.topOffset);
                        checkAllValid();
                    });
                };
            },
            init: function(){
                var self = this;
                $('#img-thumbnail').on('load', function(e){
                    $(e.currentTarget).Jcrop({
                        onChange: self.showPreview(),
                        onSelect: self.showPreview(),
                        onRelease: self.setSelect,
                        allowSelect: false,
                        minSize: [180, 180],
                        setSelect: [self.coords.x, self.coords.y, self.coords.w, self.coords.h],
                        aspectRatio: 1
                    }, function(){
                        self.jcrop_api = this;
                    });
                });
                
                $('#btn-finish-crop').click(self.finishCrop());
            }
        };
        winCrop.init();
               
        
        // ************ 自动提交
        
        // 获取validResult的偏移位置
        var getOffset = function(targetId) {
            var result = { offset : 25, topOffset : 5 };
            targetId = targetId.toString();
            switch (targetId) {
                case "expected_funding_amt":
                    result.offset = 65;
                    break;
                case "funding_stock_percent":
                    result.offset = 65;
                    break;
                case "funding_mini_unit":
                    result.offset = 115;
                    break;
                case "editguaranteehead":
                    result.offset = -90;
                    result.topOffset = 18;
                    break;
                case "addguaranteehead":
                    result.offset = -90;
                    result.topOffset = 18;
                    break;
                case "guarantee_candidate":
                    result.topOffset = -2;
                    break;
                case "ffs":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "fbl":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "ffus":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "ffd":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "fcr":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "fpcr":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "ffr":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "fsf":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "personalcreditreport":
                    result.offset = 70;
                    result.topOffset = 10;
                    break;
                case "images":
                    result.offset = 70;
                    result.topOffset = 10;
                case "guarantees":
                    result.offset = -640;
                    result.topOffset = 2;
                default:
                    break;
            }
            return result;
        }
        
        $('.ntext, select').change(function(e){
            var object = $(e.target);
            object.validResultHide();
            var isRequired = object.attr('requiredfield') === 'yes' ? true : false;
            var val = object.val();
            var targetId = object.attr('id');
            var valued = val.length > 0 ? true : false;
            if(object.get(0).tagName === 'SELECT') {
                valued = val * 1 > 0 ? true : false;
            }
            
            // 个别特殊的位置需要调整
            var offsetObj = getOffset(targetId);
            var offset = offsetObj.offset;
            var topOffset = offsetObj.topOffset;
            
            
            var data = { 'validation':0, 'key':targetId, 'val':val};
            $.post('<?php echo $this->url(array('id'=>$this->id), 'company-info')?>', data, function(result){
                result === 1 ? true : false;
                
                if(result) {
                    if (isRequired && !valued) {
                        object.validResultShow('error','必填项', offset, topOffset);
                    } else {
                        object.validResultShow('right','已更新', offset, topOffset);
                    }
                } else {
                    object.validResultShow('error','更新错误，请重试', offset, topOffset);
                }
                
                var resultObj = validBlockByObject(object);
                var tag = $("li[for=" + resultObj.blockId + "]").find('a');
                if(resultObj.result) {
                    tag.addClass('saved');
                } else {
                    tag.removeClass('saved');
                }
                
                calculateStockPrice();
            });
        });

        checkAllValid();
        
        // 编辑担保人
        $('#editguaranteebtn').click(function(e){
            var gid = findParentByClass($(e.target), 'vg').attr('gid');
            saveG(e,gid);
        });
        
        // 添加担保人
        $('#addguaranteebtn').click(function(e){
            // 判断是否可以继续添加
            if($('.addedguarantees .addedguarantee').length >= 3) {
                return;
            }
            saveG(e);
        });
        
        var saveG = function(e, gid) {
            var object = $(e.target);
            
            var container = findParentByClass(object, 'vg');
            
            var vname = container.find('.vname');
            var vemail = container.find('.vemail');
            var vphone = container.find('.vphone');
            var vrelationship = container.find('.vrelationship');
            
            var name = vname.val();
            var email = vemail.val();
            var phone = vphone.val();
            var relationship = vrelationship.val();
            var valid = true;
            
            // 判断是否已经添加了同样的email
            $('.addedguarantees .email').each(function(){
                if(email.toString() == $(this).html().toString()){
                    if(gid.length > 0 && gid == $(this).parent().attr('gid')) {
                        
                    } else {
                        alert('请不要输入重复的担保人邮箱');
                        valid = false;
                        return;
                    }
                }
            });
            if(!(name.length > 0)) {
                alert('请输入担保人姓名');
                valid = false;
            }
            if(!(email.length > 0)) {
                alert('请输入担保人邮箱');
                valid = false;
            }
            if(email == useremail) {
                alert('不可使用自己的邮箱');
                valid = false;
            }
            if(!(phone.length > 0)) {
                alert('请输入担保人电话');
                valid = false;
            }
            if(!(relationship.length > 0)) {
                alert('请输入与担保人关系');
                valid = false;
            }
            if(!valid) {
                return;
            }
            
            // 提交
            var data = { 'company_id' : companyId, 'name': name, 'email': email, 'phone': phone, 'relationship': relationship };
            if(typeof(gid) !== 'undefined') {
                data.guarantor_id = gid;
            }
            $.post('<?php echo $this->url(array(), 'save-guarantee')?>', data, function(response){
                var result = response.result;
                var btnId = "guarantees";
                var offsetObj = getOffset(btnId);
                if(result) {
                    if($('.addedguarantees .addedguarantee').length >= 3) {
                        $('#guarantees_hid').val(1);
                    }
                    $('#' + btnId).validResultShow('right','操作成功', offsetObj.offset, offsetObj.topOffset);
                    $.popupClose();
                    refreshG();
                } else {
                    $('#' + btnId).validResultShow('error','操作失败，请重试', offsetObj.offset, offsetObj.topOffset);
                }
            });
        };
        
        $('#submitbtn').click(function(e){
            var object = $(e.target);
            var resultObj = checkAllValid();
            if(resultObj.result) {
                // 验证通过
                if(confirm('确认提交公司信息？')) {
                    object.processBtn('信息提交中...');
                    // 提交
                    var data = { 'company_id' : companyId };
                    $.post('<?php echo $this->url(array(), 'submit-company') ?>', data, function(response){
                        if(response) {
                            alert('信息提交成功');
                            location.reload();
                        } else {
                            alert('提交失败，请重试');
                        }
                        object.processBtnRestore();
                    });
                }
            } else {
                var invalidId = resultObj.invalidId;
                
                if(invalidId.length <= 0) {
                    alert('开发异常：未能返回验证不通过对象');
                }
                $(invalidId).each(function(){
                    var offsetObject = getOffset(this);
                    var offset = offsetObject.offset;
                    var topOffset = offsetObject.topOffset;
                    $('#' + this).validResultShow('error', '必填项', offset, topOffset);
                });
                
                location.href = '#' + invalidId[0];
            }
        });
        
        
        $("#funding_mini_unit, #funding_stock_percent, #expected_funding_amt").change(function(){
            calculateStockPrice();
        });
        
        var calculateStockPrice = function(){
            var data= { 'company_id':companyId };
            $.post('<?php echo $this->url(array(), 'unit-perc') ?>',data, function(response) {
                if(response) {
                    var total = response.total;
                    var prev_total = response.prev_total;
                    var funding_mini_unit_perc = response.funding_mini_unit_perc;
                    
                    $('#funding_mini_unit_perc').html(funding_mini_unit_perc);
                    // set controls in popup template
                    $('#law_panel_term_company_total').html(prev_total);
                }
            });
        };
        calculateStockPrice();
        
        $("#sign_raising_term").click(function(){
            $('#law_panel_term_company_id').html($('#name').val());
            var now = new Date();
            $('#law_panel_today').html(now.getFullYear() + "年" + now.getMonth() + "月" + now.getDay() + "日");
            $('#law_panel_representative').html($('#representative').val());
            $.popup({ title: '借贷及债转股条款' }, 'law_panel_term');
        });
        
        $('.toaddg').click(function(obj) {
            var object = $(obj);
            $.popup({title:'添加担保人'},"ag");
        });
        $('.addedg .edit').click(function(e) {
            var object = $(e.target);
            var wrapper = findParentByClass(object, 'addedg');
            var gid = wrapper.attr('gid');
            
            // gid 保存在 .editguarantee 上
            $('#eg').find('.editguarantee').attr('gid',gid);
            $('#eg').find('.vname').val(wrapper.find('.name').html());
            $('#eg').find('.vrelationship').val(wrapper.find('.relationship').html());
            $('#eg').find('.vemail').val(wrapper.find('.email').html());
            $('#eg').find('.vphone').val(wrapper.find('.phone').html());
            
            $.popup({title:'编辑担保人'},"eg");
        });
        
        
        var refreshG = function(func) {
            var wrapper = $('.addedguarantees');
            wrapper.empty();
            var maxNum = 3;
            var data = { 'company_id' : companyId };
            $.post('<?php echo $this->url(array(), 'get-guarantees-by-company-id') ?>', data, function(response){
                var responseLength = $(response).length;
                if(responseLength > 0) {
                    // 已有担保人，添加担保人
                    $(response).each(function(){
                        var newObj = $($('.addedg')[0]).clone(true);
                        wrapper.append(newObj);
                        newObj.attr('gid', this.id);
                        newObj.find('.name').html(this.name);
                        newObj.find('.phone').html(this.phone);
                        newObj.find('.email').html(this.email);
                        newObj.find('.relationship').html(this.relationship);
                        newObj.show();
                    });
                    // 补上剩下的
                    if(responseLength < maxNum) {
                        
                        for(var i = 0; i < (maxNum - responseLength); i++) {
                            var newObj = $($('.toaddg')[0]).clone(true);
                            wrapper.append(newObj);
                            newObj.show();
                        }
                    }
                    
                    if($('.addedguarantees .addedg').length == maxNum) {
                        $('#guarantees_hid').val(1);
                    }
                } else {
                    // 无担保人
                    for(var i=0; i < maxNum; i++) {
                        var newObj = $($('.toaddg')[0]).clone(true);
                        wrapper.append(newObj);
                        newObj.show();
                    }
                }
                checkAllValid();
                if(typeof(func) !== "undefined") {
                    func();
                }
            });
        };
        refreshG();
        
        $('.videoplaybtn').click(function(e){
            // 视频效果展示
            var code = $(e.target).parent().find('.ntext').val();
            if(code.length > 0) {
                $('#video_show_panel').html(code);
                $.popup({},'video_show_panel');
            }
        });
    })(jQuery);
</script>