<?php
namespace Documents;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/** @ODM\EmbeddedDocument */
class CompanyDoc extends AbstractDocument{
    
    /** @ODM\String */
    protected $filename;
    
    /** @ODM\String */
    protected $angelname; // the file name generated by system
    
    /** @ODM\String */
    protected $path; // 这个变量可以看作是一个占位变量，这个变量不会真正保存值，只是用来保存临时值

    /** @ODM\Boolean */
    protected $active_bln = true;    
}
